// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package direct

import (
	"context"

	"github.com/runforyou-ai/luway/internal/appservice"
)

// ReportComputerCapabilities 上报本电脑的执行能力、执行器版本与同时执行的操作上限。
func (b *Backend) ReportComputerCapabilities(ctx context.Context, meta appservice.RequestMeta, input appservice.ComputerCapabilitiesInput) error {
	computer, err := b.ops.authenticateComputer(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.ReportComputerCapabilities(ctx, meta, computer, input)
}

// ClaimComputerOperations 领取派发给本电脑的待执行操作。
func (b *Backend) ClaimComputerOperations(ctx context.Context, meta appservice.RequestMeta, input appservice.ComputerClaimInput) (appservice.ComputerOperationList, error) {
	computer, err := b.ops.authenticateComputer(ctx, meta)
	if err != nil {
		var zero appservice.ComputerOperationList
		return zero, err
	}
	return appservice.WithNormalizedSlices(b.ops.ClaimComputerOperations(ctx, meta, computer, input))
}

// CompleteComputerOperation 上报本电脑执行一次操作的结果。
func (b *Backend) CompleteComputerOperation(ctx context.Context, meta appservice.RequestMeta, operationID string, input appservice.ComputerOutcomeInput) error {
	computer, err := b.ops.authenticateComputer(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.CompleteComputerOperation(ctx, meta, computer, operationID, input)
}
