// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package direct

import (
	"context"

	"github.com/runforyou-ai/luway/internal/appservice"
	"github.com/runforyou-ai/luway/internal/appservice/dispatch"
	"github.com/runforyou-ai/luway/internal/common/logscope"
)

// GetComputerRealtimeConnection 换取本电脑的短期实时凭据和工作通知频道。
func (b *Backend) GetComputerRealtimeConnection(ctx context.Context, meta appservice.RequestMeta) (_ appservice.RealtimePeerConnection, err error) {
	ctx = logscope.WithOperation(ctx, "GetComputerRealtimeConnection")
	defer dispatch.Settle(&ctx, &err, dispatch.InternalError(meta))
	ctx, computer, err := b.ops.authenticateComputer(ctx, meta)
	if err != nil {
		var zero appservice.RealtimePeerConnection
		return zero, err
	}
	return b.ops.GetComputerRealtimeConnection(ctx, meta, computer)
}

// HeartbeatComputer 以当前电脑凭据记录最近在线时间。
func (b *Backend) HeartbeatComputer(ctx context.Context, meta appservice.RequestMeta) (err error) {
	ctx = logscope.WithOperation(ctx, "HeartbeatComputer")
	defer dispatch.Settle(&ctx, &err, dispatch.InternalError(meta))
	ctx, computer, err := b.ops.authenticateComputer(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.HeartbeatComputer(ctx, meta, computer)
}

// ReportComputerCapabilities 上报本电脑的操作系统平台、执行能力、执行器版本与同时执行的操作上限。
func (b *Backend) ReportComputerCapabilities(ctx context.Context, meta appservice.RequestMeta, input appservice.ComputerCapabilitiesInput) (err error) {
	ctx = logscope.WithOperation(ctx, "ReportComputerCapabilities")
	defer dispatch.Settle(&ctx, &err, dispatch.InternalError(meta))
	ctx, computer, err := b.ops.authenticateComputer(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.ReportComputerCapabilities(ctx, meta, computer, input)
}

// ClaimComputerOperations 领取派发给本电脑的待执行操作，并返回应当中止的操作。
func (b *Backend) ClaimComputerOperations(ctx context.Context, meta appservice.RequestMeta, input appservice.ComputerClaimInput) (_ appservice.ComputerOperationList, err error) {
	ctx = logscope.WithOperation(ctx, "ClaimComputerOperations")
	defer dispatch.Settle(&ctx, &err, dispatch.InternalError(meta))
	ctx, computer, err := b.ops.authenticateComputer(ctx, meta)
	if err != nil {
		var zero appservice.ComputerOperationList
		return zero, err
	}
	return b.ops.ClaimComputerOperations(ctx, meta, computer, input)
}

// CompleteComputerOperation 上报本电脑执行一次操作的结果。
func (b *Backend) CompleteComputerOperation(ctx context.Context, meta appservice.RequestMeta, operationID string, input appservice.ComputerOutcomeInput) (err error) {
	ctx = logscope.WithOperation(ctx, "CompleteComputerOperation")
	defer dispatch.Settle(&ctx, &err, dispatch.InternalError(meta))
	ctx, computer, err := b.ops.authenticateComputer(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.CompleteComputerOperation(ctx, meta, computer, operationID, input)
}

// ReportComputerOperationUpdates 上报本电脑执行中的一次操作的过程更新。
func (b *Backend) ReportComputerOperationUpdates(ctx context.Context, meta appservice.RequestMeta, operationID string, input appservice.ComputerUpdatesInput) (err error) {
	ctx = logscope.WithOperation(ctx, "ReportComputerOperationUpdates")
	defer dispatch.Settle(&ctx, &err, dispatch.InternalError(meta))
	ctx, computer, err := b.ops.authenticateComputer(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.ReportComputerOperationUpdates(ctx, meta, computer, operationID, input)
}

// ListComputerSharedFiles 返回本电脑执行中的命令或本机 Agent 轮次所属会话共享文件区的文件清单与下载地址。
func (b *Backend) ListComputerSharedFiles(ctx context.Context, meta appservice.RequestMeta, operationID string) (_ appservice.ComputerSharedFileList, err error) {
	ctx = logscope.WithOperation(ctx, "ListComputerSharedFiles")
	defer dispatch.Settle(&ctx, &err, dispatch.InternalError(meta))
	ctx, computer, err := b.ops.authenticateComputer(ctx, meta)
	if err != nil {
		var zero appservice.ComputerSharedFileList
		return zero, err
	}
	return b.ops.ListComputerSharedFiles(ctx, meta, computer, operationID)
}

// CreateComputerSharedUpload 为写回会话共享文件区中的一个文件创建内容上传。
func (b *Backend) CreateComputerSharedUpload(ctx context.Context, meta appservice.RequestMeta, operationID string, input appservice.ComputerSharedUploadInput) (_ appservice.ComputerSharedUpload, err error) {
	ctx = logscope.WithOperation(ctx, "CreateComputerSharedUpload")
	defer dispatch.Settle(&ctx, &err, dispatch.InternalError(meta))
	ctx, computer, err := b.ops.authenticateComputer(ctx, meta)
	if err != nil {
		var zero appservice.ComputerSharedUpload
		return zero, err
	}
	return b.ops.CreateComputerSharedUpload(ctx, meta, computer, operationID, input)
}

// CommitComputerSharedFile 把上传完成的内容按同步基准写回会话共享文件区。
func (b *Backend) CommitComputerSharedFile(ctx context.Context, meta appservice.RequestMeta, operationID string, input appservice.ComputerSharedCommitInput) (_ appservice.ComputerSharedCommit, err error) {
	ctx = logscope.WithOperation(ctx, "CommitComputerSharedFile")
	defer dispatch.Settle(&ctx, &err, dispatch.InternalError(meta))
	ctx, computer, err := b.ops.authenticateComputer(ctx, meta)
	if err != nil {
		var zero appservice.ComputerSharedCommit
		return zero, err
	}
	return b.ops.CommitComputerSharedFile(ctx, meta, computer, operationID, input)
}

// RequestComputerPermission 上报本电脑上本机 Agent 在执行中的一轮里请求的权限。
func (b *Backend) RequestComputerPermission(ctx context.Context, meta appservice.RequestMeta, operationID string, input appservice.ComputerPermissionInput) (err error) {
	ctx = logscope.WithOperation(ctx, "RequestComputerPermission")
	defer dispatch.Settle(&ctx, &err, dispatch.InternalError(meta))
	ctx, computer, err := b.ops.authenticateComputer(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.RequestComputerPermission(ctx, meta, computer, operationID, input)
}
