// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package direct

import (
	"context"

	"github.com/runforyou-ai/luway/internal/appservice"
)

// GetDeviceWork 返回本设备的工作水位与待领取运行。
func (b *Backend) GetDeviceWork(ctx context.Context, meta appservice.RequestMeta) (appservice.DeviceWork, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero appservice.DeviceWork
		return zero, err
	}
	return appservice.WithNormalizedSlices(b.ops.GetDeviceWork(ctx, meta, device))
}

// ReportDeviceLocalAgents 上报本设备上已安装且可用的本机 Agent。
func (b *Backend) ReportDeviceLocalAgents(ctx context.Context, meta appservice.RequestMeta, input appservice.DeviceLocalAgentsInput) error {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.ReportDeviceLocalAgents(ctx, meta, device, input)
}

// ClaimDeviceRun 领取派发给本设备的排队运行并取得租约。
func (b *Backend) ClaimDeviceRun(ctx context.Context, meta appservice.RequestMeta, runID string) (appservice.DeviceRunClaim, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero appservice.DeviceRunClaim
		return zero, err
	}
	return appservice.WithNormalizedSlices(b.ops.ClaimDeviceRun(ctx, meta, device, runID))
}

// RenewDeviceRunLease 为本设备持有的运行续租，运行已结束时返回 ended。
func (b *Backend) RenewDeviceRunLease(ctx context.Context, meta appservice.RequestMeta, runID string) (appservice.DeviceRunLease, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero appservice.DeviceRunLease
		return zero, err
	}
	return appservice.WithNormalizedSlices(b.ops.RenewDeviceRunLease(ctx, meta, device, runID))
}

// PeekDeviceRunInputs 返回本设备持有运行尚未认领的输入信号。
func (b *Backend) PeekDeviceRunInputs(ctx context.Context, meta appservice.RequestMeta, runID string, input appservice.DeviceRunInputPeekInput) (appservice.DeviceRunInputSignals, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero appservice.DeviceRunInputSignals
		return zero, err
	}
	return appservice.WithNormalizedSlices(b.ops.PeekDeviceRunInputs(ctx, meta, device, runID, input))
}

// ClaimDeviceRunInputs 为本设备持有的运行认领输入并返回截至该边界的上下文消息。
func (b *Backend) ClaimDeviceRunInputs(ctx context.Context, meta appservice.RequestMeta, runID string, input appservice.DeviceRunInputClaimInput) (appservice.DeviceRunClaimedInput, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero appservice.DeviceRunClaimedInput
		return zero, err
	}
	return appservice.WithNormalizedSlices(b.ops.ClaimDeviceRunInputs(ctx, meta, device, runID, input))
}

// SearchDeviceRunKnowledge 在本设备持有运行绑定的知识库中检索。
func (b *Backend) SearchDeviceRunKnowledge(ctx context.Context, meta appservice.RequestMeta, runID string, input appservice.DeviceRunKnowledgeSearchInput) (appservice.DeviceRunKnowledgeSearchResult, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero appservice.DeviceRunKnowledgeSearchResult
		return zero, err
	}
	return appservice.WithNormalizedSlices(b.ops.SearchDeviceRunKnowledge(ctx, meta, device, runID, input))
}

// GetDeviceRunMemory 返回本设备持有运行所属个人 AI 员工的记忆，有效配置未启用记忆时为空。
func (b *Backend) GetDeviceRunMemory(ctx context.Context, meta appservice.RequestMeta, runID string) (appservice.DeviceRunMemory, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero appservice.DeviceRunMemory
		return zero, err
	}
	return appservice.WithNormalizedSlices(b.ops.GetDeviceRunMemory(ctx, meta, device, runID))
}

// SearchDeviceRunWeb 用企业配置的搜索服务为本设备持有的运行搜索互联网。
func (b *Backend) SearchDeviceRunWeb(ctx context.Context, meta appservice.RequestMeta, runID string, input appservice.DeviceRunWebSearchInput) (appservice.DeviceRunWebSearchResult, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero appservice.DeviceRunWebSearchResult
		return zero, err
	}
	return appservice.WithNormalizedSlices(b.ops.SearchDeviceRunWeb(ctx, meta, device, runID, input))
}

// ListDeviceRunMCPTools 列出本设备持有运行绑定的企业 MCP 服务及其工具目录，不可用的服务不列出。
func (b *Backend) ListDeviceRunMCPTools(ctx context.Context, meta appservice.RequestMeta, runID string) (appservice.DeviceRunMCPToolList, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero appservice.DeviceRunMCPToolList
		return zero, err
	}
	return appservice.WithNormalizedSlices(b.ops.ListDeviceRunMCPTools(ctx, meta, device, runID))
}

// CallDeviceRunMCPTool 为本设备持有的运行调用企业 MCP 工具。
func (b *Backend) CallDeviceRunMCPTool(ctx context.Context, meta appservice.RequestMeta, runID string, input appservice.DeviceRunMCPToolCallInput) (appservice.DeviceRunMCPToolCallResult, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero appservice.DeviceRunMCPToolCallResult
		return zero, err
	}
	return appservice.WithNormalizedSlices(b.ops.CallDeviceRunMCPTool(ctx, meta, device, runID, input))
}

// CompleteDeviceRun 以成功结果收尾本设备持有的运行。
func (b *Backend) CompleteDeviceRun(ctx context.Context, meta appservice.RequestMeta, runID string, input appservice.DeviceRunResultInput) error {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.CompleteDeviceRun(ctx, meta, device, runID, input)
}

// FailDeviceRun 以失败原因收尾派发给本设备的运行。
func (b *Backend) FailDeviceRun(ctx context.Context, meta appservice.RequestMeta, runID string, input appservice.DeviceRunFailureInput) error {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.FailDeviceRun(ctx, meta, device, runID, input)
}
