// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package direct

import (
	"context"

	"github.com/runforyou-ai/luway/internal/appservice"
)

// LoadDeployment 返回部署形态与部署地址。
func (b *OperatorBackend) LoadDeployment(ctx context.Context, meta appservice.OperatorRequestMeta) (appservice.OperatorDeployment, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero appservice.OperatorDeployment
		return zero, err
	}
	return appservice.WithNormalizedSlices(b.ops.LoadDeployment(ctx, meta, identity))
}

// ListOrganizations 按条件分页返回工作区摘要。
func (b *OperatorBackend) ListOrganizations(ctx context.Context, meta appservice.OperatorRequestMeta, input appservice.OperatorOrganizationListInput) (appservice.OperatorOrganizationList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero appservice.OperatorOrganizationList
		return zero, err
	}
	return appservice.WithNormalizedSlices(b.ops.ListOrganizations(ctx, meta, identity, input))
}

// GetOrganization 返回工作区摘要与状态。
func (b *OperatorBackend) GetOrganization(ctx context.Context, meta appservice.OperatorRequestMeta, organizationID string) (appservice.OperatorOrganization, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero appservice.OperatorOrganization
		return zero, err
	}
	return appservice.WithNormalizedSlices(b.ops.GetOrganization(ctx, meta, identity, organizationID))
}
