changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: 破坏性变更
      labels:
        - breaking-change
    - title: 新功能
      labels:
        - enhancement
    - title: 问题修复
      labels:
        - bug
    - title: 其他变更
      labels:
        - "*"
