// Code generated by appservicegen. DO NOT EDIT.

//go:build !server && !ios && !android

package executor

import (
	"context"
	"net/http"
	"net/url"

	"github.com/runforyou-ai/luway/internal/appservice"
)

// getComputerRealtimeConnection 换取本电脑的短期实时凭据和工作通知频道。
func (c *client) getComputerRealtimeConnection(ctx context.Context) (appservice.RealtimePeerConnection, error) {
	var output appservice.RealtimePeerConnection
	err := c.do(ctx, http.MethodGet, "/computer/realtime-connection", nil, &output)
	return output, err
}

// heartbeatComputer 以当前电脑凭据记录最近在线时间。
func (c *client) heartbeatComputer(ctx context.Context) error {
	return c.do(ctx, http.MethodPost, "/computer/heartbeat", nil, nil)
}

// reportComputerCapabilities 上报本电脑的操作系统平台、执行能力、执行器版本与同时执行的操作上限。
func (c *client) reportComputerCapabilities(ctx context.Context, input appservice.ComputerCapabilitiesInput) error {
	return c.do(ctx, http.MethodPut, "/computer/capabilities", input, nil)
}

// claimComputerOperations 领取派发给本电脑的待执行操作，并返回应当中止的操作。
func (c *client) claimComputerOperations(ctx context.Context, input appservice.ComputerClaimInput) (appservice.ComputerOperationList, error) {
	var output appservice.ComputerOperationList
	err := c.do(ctx, http.MethodPost, "/computer/operations/claim", input, &output)
	return output, err
}

// completeComputerOperation 上报本电脑执行一次操作的结果。
func (c *client) completeComputerOperation(ctx context.Context, operationID string, input appservice.ComputerOutcomeInput) error {
	return c.do(ctx, http.MethodPost, "/computer/operations/"+url.PathEscape(operationID)+"/result", input, nil)
}

// reportComputerOperationUpdates 上报本电脑执行中的一次操作的过程更新。
func (c *client) reportComputerOperationUpdates(ctx context.Context, operationID string, input appservice.ComputerUpdatesInput) error {
	return c.do(ctx, http.MethodPost, "/computer/operations/"+url.PathEscape(operationID)+"/updates", input, nil)
}

// listComputerSharedFiles 返回本电脑执行中的命令或本机 Agent 轮次所属会话共享文件区的文件清单与下载地址。
func (c *client) listComputerSharedFiles(ctx context.Context, operationID string) (appservice.ComputerSharedFileList, error) {
	var output appservice.ComputerSharedFileList
	err := c.do(ctx, http.MethodGet, "/computer/operations/"+url.PathEscape(operationID)+"/shared-files", nil, &output)
	return output, err
}

// createComputerSharedUpload 为写回会话共享文件区中的一个文件创建内容上传。
func (c *client) createComputerSharedUpload(ctx context.Context, operationID string, input appservice.ComputerSharedUploadInput) (appservice.ComputerSharedUpload, error) {
	var output appservice.ComputerSharedUpload
	err := c.do(ctx, http.MethodPost, "/computer/operations/"+url.PathEscape(operationID)+"/shared-files/uploads", input, &output)
	return output, err
}

// commitComputerSharedFile 把上传完成的内容按同步基准写回会话共享文件区。
func (c *client) commitComputerSharedFile(ctx context.Context, operationID string, input appservice.ComputerSharedCommitInput) (appservice.ComputerSharedCommit, error) {
	var output appservice.ComputerSharedCommit
	err := c.doUnbounded(ctx, http.MethodPost, "/computer/operations/"+url.PathEscape(operationID)+"/shared-files/commit", input, &output)
	return output, err
}

// requestComputerPermission 上报本电脑上本机 Agent 在执行中的一轮里请求的权限。
func (c *client) requestComputerPermission(ctx context.Context, operationID string, input appservice.ComputerPermissionInput) error {
	return c.do(ctx, http.MethodPost, "/computer/operations/"+url.PathEscape(operationID)+"/permissions", input, nil)
}
