// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package api

import (
	"net/http"

	"github.com/runforyou-ai/luway/internal/appservice"
	"github.com/runforyou-ai/luway/internal/httpcodec"
)

// registerGeneratedComputerRoutes 注册由 appservicegen 生成的执行器路由。
func (s *Service) registerGeneratedComputerRoutes(handle func(string, http.HandlerFunc)) {
	handle("GET /computer/realtime-connection", s.getComputerRealtimeConnection)
	handle("POST /computer/heartbeat", s.heartbeatComputer)
	handle("PUT /computer/capabilities", s.reportComputerCapabilities)
	handle("POST /computer/operations/claim", s.claimComputerOperations)
	handle("POST /computer/operations/{operationID}/result", s.completeComputerOperation)
	handle("POST /computer/operations/{operationID}/updates", s.reportComputerOperationUpdates)
	handle("GET /computer/operations/{operationID}/shared-files", s.listComputerSharedFiles)
	handle("POST /computer/operations/{operationID}/shared-files/uploads", s.createComputerSharedUpload)
	handle("POST /computer/operations/{operationID}/shared-files/commit", s.commitComputerSharedFile)
	handle("POST /computer/operations/{operationID}/permissions", s.requestComputerPermission)
}

// getComputerRealtimeConnection 换取本电脑的短期实时凭据和工作通知频道。
func (s *Service) getComputerRealtimeConnection(writer http.ResponseWriter, request *http.Request) {
	output, err := s.computers.GetComputerRealtimeConnection(request.Context(), httpcodec.RequestMeta(request))
	httpcodec.WriteResult(writer, request, http.StatusOK, output, err)
}

// heartbeatComputer 以当前电脑凭据记录最近在线时间。
func (s *Service) heartbeatComputer(writer http.ResponseWriter, request *http.Request) {
	httpcodec.WriteEmpty(writer, request, s.computers.HeartbeatComputer(request.Context(), httpcodec.RequestMeta(request)))
}

// reportComputerCapabilities 上报本电脑的操作系统平台、执行能力、执行器版本与同时执行的操作上限。
func (s *Service) reportComputerCapabilities(writer http.ResponseWriter, request *http.Request) {
	var input appservice.ComputerCapabilitiesInput
	if !httpcodec.BindJSON(writer, request, &input) {
		return
	}
	httpcodec.WriteEmpty(writer, request, s.computers.ReportComputerCapabilities(request.Context(), httpcodec.RequestMeta(request), input))
}

// claimComputerOperations 领取派发给本电脑的待执行操作，并返回应当中止的操作。
func (s *Service) claimComputerOperations(writer http.ResponseWriter, request *http.Request) {
	var input appservice.ComputerClaimInput
	if !httpcodec.BindJSON(writer, request, &input) {
		return
	}
	output, err := s.computers.ClaimComputerOperations(request.Context(), httpcodec.RequestMeta(request), input)
	httpcodec.WriteResult(writer, request, http.StatusOK, output, err)
}

// completeComputerOperation 上报本电脑执行一次操作的结果。
func (s *Service) completeComputerOperation(writer http.ResponseWriter, request *http.Request) {
	var input appservice.ComputerOutcomeInput
	if !httpcodec.BindJSON(writer, request, &input) {
		return
	}
	httpcodec.WriteEmpty(writer, request, s.computers.CompleteComputerOperation(request.Context(), httpcodec.RequestMeta(request), request.PathValue("operationID"), input))
}

// reportComputerOperationUpdates 上报本电脑执行中的一次操作的过程更新。
func (s *Service) reportComputerOperationUpdates(writer http.ResponseWriter, request *http.Request) {
	var input appservice.ComputerUpdatesInput
	if !httpcodec.BindJSON(writer, request, &input) {
		return
	}
	httpcodec.WriteEmpty(writer, request, s.computers.ReportComputerOperationUpdates(request.Context(), httpcodec.RequestMeta(request), request.PathValue("operationID"), input))
}

// listComputerSharedFiles 返回本电脑执行中的命令或本机 Agent 轮次所属会话共享文件区的文件清单与下载地址。
func (s *Service) listComputerSharedFiles(writer http.ResponseWriter, request *http.Request) {
	output, err := s.computers.ListComputerSharedFiles(request.Context(), httpcodec.RequestMeta(request), request.PathValue("operationID"))
	httpcodec.WriteResult(writer, request, http.StatusOK, output, err)
}

// createComputerSharedUpload 为写回会话共享文件区中的一个文件创建内容上传。
func (s *Service) createComputerSharedUpload(writer http.ResponseWriter, request *http.Request) {
	var input appservice.ComputerSharedUploadInput
	if !httpcodec.BindJSON(writer, request, &input) {
		return
	}
	output, err := s.computers.CreateComputerSharedUpload(request.Context(), httpcodec.RequestMeta(request), request.PathValue("operationID"), input)
	httpcodec.WriteResult(writer, request, http.StatusCreated, output, err)
}

// commitComputerSharedFile 把上传完成的内容按同步基准写回会话共享文件区。
func (s *Service) commitComputerSharedFile(writer http.ResponseWriter, request *http.Request) {
	var input appservice.ComputerSharedCommitInput
	if !httpcodec.BindJSON(writer, request, &input) {
		return
	}
	output, err := s.computers.CommitComputerSharedFile(request.Context(), httpcodec.RequestMeta(request), request.PathValue("operationID"), input)
	httpcodec.WriteResult(writer, request, http.StatusOK, output, err)
}

// requestComputerPermission 上报本电脑上本机 Agent 在执行中的一轮里请求的权限。
func (s *Service) requestComputerPermission(writer http.ResponseWriter, request *http.Request) {
	var input appservice.ComputerPermissionInput
	if !httpcodec.BindJSON(writer, request, &input) {
		return
	}
	httpcodec.WriteEmpty(writer, request, s.computers.RequestComputerPermission(request.Context(), httpcodec.RequestMeta(request), request.PathValue("operationID"), input))
}
