// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/runforyou-ai/luway/internal/appservice"
)

// registerGeneratedComputerRoutes 注册由 appservicegen 生成的执行器路由。
func (s *Service) registerGeneratedComputerRoutes(router *gin.Engine) {
	router.PUT("/computer/capabilities", s.reportComputerCapabilities)
	router.POST("/computer/operations/claim", s.claimComputerOperations)
	router.POST("/computer/operations/:operationID/result", s.completeComputerOperation)
}

// reportComputerCapabilities 上报本电脑的执行能力、执行器版本与同时执行的操作上限。
func (s *Service) reportComputerCapabilities(c *gin.Context) {
	var input appservice.ComputerCapabilitiesInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.computers.ReportComputerCapabilities(c.Request.Context(), requestMeta(c), input))
}

// claimComputerOperations 领取派发给本电脑的待执行操作。
func (s *Service) claimComputerOperations(c *gin.Context) {
	var input appservice.ComputerClaimInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.computers.ClaimComputerOperations(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// completeComputerOperation 上报本电脑执行一次操作的结果。
func (s *Service) completeComputerOperation(c *gin.Context) {
	var input appservice.ComputerOutcomeInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.computers.CompleteComputerOperation(c.Request.Context(), requestMeta(c), c.Param("operationID"), input))
}
