// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/runforyou-ai/luway/internal/appservice"
)

// registerGeneratedDeviceRunRoutes 注册由 appservicegen 生成的设备运行期路由。
func (s *Service) registerGeneratedDeviceRunRoutes(router *gin.Engine) {
	router.GET("/devices/current/work", s.getDeviceWork)
	router.PUT("/devices/current/local-agents", s.reportDeviceLocalAgents)
	router.POST("/agent-runs/:runID/claim", s.claimDeviceRun)
	router.POST("/agent-runs/:runID/lease", s.renewDeviceRunLease)
	router.GET("/agent-runs/:runID/inputs", s.peekDeviceRunInputs)
	router.POST("/agent-runs/:runID/inputs/claim", s.claimDeviceRunInputs)
	router.POST("/agent-runs/:runID/knowledge/search", s.searchDeviceRunKnowledge)
	router.GET("/agent-runs/:runID/memory", s.getDeviceRunMemory)
	router.POST("/agent-runs/:runID/web/search", s.searchDeviceRunWeb)
	router.GET("/agent-runs/:runID/mcp/tools", s.listDeviceRunMCPTools)
	router.POST("/agent-runs/:runID/mcp/tools/call", s.callDeviceRunMCPTool)
	router.POST("/agent-runs/:runID/result", s.completeDeviceRun)
	router.POST("/agent-runs/:runID/failure", s.failDeviceRun)
}

// getDeviceWork 返回本设备的工作水位与待领取运行。
func (s *Service) getDeviceWork(c *gin.Context) {
	output, err := s.deviceRuns.GetDeviceWork(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// reportDeviceLocalAgents 上报本设备上已安装且可用的本机 Agent。
func (s *Service) reportDeviceLocalAgents(c *gin.Context) {
	var input appservice.DeviceLocalAgentsInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.deviceRuns.ReportDeviceLocalAgents(c.Request.Context(), requestMeta(c), input))
}

// claimDeviceRun 领取派发给本设备的排队运行并取得租约。
func (s *Service) claimDeviceRun(c *gin.Context) {
	output, err := s.deviceRuns.ClaimDeviceRun(c.Request.Context(), requestMeta(c), c.Param("runID"))
	writeResult(c, http.StatusOK, output, err)
}

// renewDeviceRunLease 为本设备持有的运行续租，运行已结束时返回 ended。
func (s *Service) renewDeviceRunLease(c *gin.Context) {
	output, err := s.deviceRuns.RenewDeviceRunLease(c.Request.Context(), requestMeta(c), c.Param("runID"))
	writeResult(c, http.StatusOK, output, err)
}

// peekDeviceRunInputs 返回本设备持有运行尚未认领的输入信号。
func (s *Service) peekDeviceRunInputs(c *gin.Context) {
	input, ok := bindDeviceRunDeviceRunInputPeekInputQuery(c)
	if !ok {
		return
	}
	output, err := s.deviceRuns.PeekDeviceRunInputs(c.Request.Context(), requestMeta(c), c.Param("runID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// claimDeviceRunInputs 为本设备持有的运行认领输入并返回截至该边界的上下文消息。
func (s *Service) claimDeviceRunInputs(c *gin.Context) {
	var input appservice.DeviceRunInputClaimInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.deviceRuns.ClaimDeviceRunInputs(c.Request.Context(), requestMeta(c), c.Param("runID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// searchDeviceRunKnowledge 在本设备持有运行绑定的知识库中检索。
func (s *Service) searchDeviceRunKnowledge(c *gin.Context) {
	var input appservice.DeviceRunKnowledgeSearchInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.deviceRuns.SearchDeviceRunKnowledge(c.Request.Context(), requestMeta(c), c.Param("runID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// getDeviceRunMemory 返回本设备持有运行所属个人 AI 员工的记忆，有效配置未启用记忆时为空。
func (s *Service) getDeviceRunMemory(c *gin.Context) {
	output, err := s.deviceRuns.GetDeviceRunMemory(c.Request.Context(), requestMeta(c), c.Param("runID"))
	writeResult(c, http.StatusOK, output, err)
}

// searchDeviceRunWeb 用企业配置的搜索服务为本设备持有的运行搜索互联网。
func (s *Service) searchDeviceRunWeb(c *gin.Context) {
	var input appservice.DeviceRunWebSearchInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.deviceRuns.SearchDeviceRunWeb(c.Request.Context(), requestMeta(c), c.Param("runID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// listDeviceRunMCPTools 列出本设备持有运行绑定的企业 MCP 服务及其工具目录，不可用的服务不列出。
func (s *Service) listDeviceRunMCPTools(c *gin.Context) {
	output, err := s.deviceRuns.ListDeviceRunMCPTools(c.Request.Context(), requestMeta(c), c.Param("runID"))
	writeResult(c, http.StatusOK, output, err)
}

// callDeviceRunMCPTool 为本设备持有的运行调用企业 MCP 工具。
func (s *Service) callDeviceRunMCPTool(c *gin.Context) {
	var input appservice.DeviceRunMCPToolCallInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.deviceRuns.CallDeviceRunMCPTool(c.Request.Context(), requestMeta(c), c.Param("runID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// completeDeviceRun 以成功结果收尾本设备持有的运行。
func (s *Service) completeDeviceRun(c *gin.Context) {
	var input appservice.DeviceRunResultInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.deviceRuns.CompleteDeviceRun(c.Request.Context(), requestMeta(c), c.Param("runID"), input))
}

// failDeviceRun 以失败原因收尾派发给本设备的运行。
func (s *Service) failDeviceRun(c *gin.Context) {
	var input appservice.DeviceRunFailureInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.deviceRuns.FailDeviceRun(c.Request.Context(), requestMeta(c), c.Param("runID"), input))
}

// bindDeviceRunDeviceRunInputPeekInputQuery 从查询参数解析 appservice.DeviceRunInputPeekInput。
func bindDeviceRunDeviceRunInputPeekInputQuery(c *gin.Context) (appservice.DeviceRunInputPeekInput, bool) {
	afterSeq, ok := positiveQueryInteger(c, "afterSeq", 0)
	if !ok {
		return appservice.DeviceRunInputPeekInput{}, false
	}
	return appservice.DeviceRunInputPeekInput{
		AfterSeq: afterSeq,
	}, true
}
