// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/runforyou-ai/luway/internal/appservice"
)

// registerGeneratedOperatorRoutes 注册由 appservicegen 生成的运营路由。
func (s *OperatorService) registerGeneratedOperatorRoutes(router *gin.Engine) {
	router.GET("/deployment", s.loadDeployment)
	router.GET("/organizations", s.listOrganizations)
	router.GET("/organizations/:organizationID", s.getOrganization)
}

// loadDeployment 返回部署形态与部署地址。
func (s *OperatorService) loadDeployment(c *gin.Context) {
	output, err := s.application.LoadDeployment(c.Request.Context(), operatorRequestMeta(c))
	writeOperatorResult(c, http.StatusOK, output, err)
}

// listOrganizations 按条件分页返回工作区摘要。
func (s *OperatorService) listOrganizations(c *gin.Context) {
	input, ok := bindOperatorOperatorOrganizationListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListOrganizations(c.Request.Context(), operatorRequestMeta(c), input)
	writeOperatorResult(c, http.StatusOK, output, err)
}

// getOrganization 返回工作区摘要与状态。
func (s *OperatorService) getOrganization(c *gin.Context) {
	output, err := s.application.GetOrganization(c.Request.Context(), operatorRequestMeta(c), c.Param("organizationID"))
	writeOperatorResult(c, http.StatusOK, output, err)
}

// bindOperatorOperatorOrganizationListInputQuery 从查询参数解析 appservice.OperatorOrganizationListInput。
func bindOperatorOperatorOrganizationListInputQuery(c *gin.Context) (appservice.OperatorOrganizationListInput, bool) {
	page, ok := positiveOperatorQueryInteger(c, "page", 1)
	if !ok {
		return appservice.OperatorOrganizationListInput{}, false
	}
	pageSize, ok := positiveOperatorQueryInteger(c, "pageSize", 50)
	if !ok {
		return appservice.OperatorOrganizationListInput{}, false
	}
	return appservice.OperatorOrganizationListInput{
		Query:           c.Query("query"),
		LifecycleStatus: optionalEnum[appservice.OrganizationLifecycleStatus](c.Query("lifecycleStatus")),
		Page:            page,
		PageSize:        pageSize,
	}, true
}
