// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package api

import (
	"net/http"

	"github.com/runforyou-ai/luway/internal/appservice"
)

// registerGeneratedWebsiteVisitorRoutes 注册由 appservicegen 生成的网站 Messenger 公开路由。
func (s *Service) registerGeneratedWebsiteVisitorRoutes(handle func(string, http.HandlerFunc)) {
	handle("GET /public/website-channels/{channelID}/realtime-connection", s.websiteVisitorGetVisitorRealtimeConnection)
	handle("GET /public/website-channels/{channelID}/conversations", s.websiteVisitorListConversations)
	handle("POST /public/website-channels/{channelID}/messages", s.websiteVisitorSendTextMessage)
	handle("POST /public/website-channels/{channelID}/attachment-messages", s.websiteVisitorSendAttachmentMessage)
	handle("POST /public/website-channels/{channelID}/attachments", s.websiteVisitorCreateAttachmentUpload)
	handle("POST /public/website-channels/{channelID}/attachments/{fileID}", s.websiteVisitorCompleteAttachmentUpload)
	handle("GET /public/website-channels/{channelID}/conversations/{conversationID}/messages/{messageID}/attachment", s.websiteVisitorGetMessageAttachment)
	handle("GET /public/website-channels/{channelID}/conversations/{conversationID}/messages", s.websiteVisitorListMessages)
	handle("POST /public/website-channels/{channelID}/conversations/{conversationID}/typing", s.websiteVisitorReportTyping)
	handle("POST /public/website-channels/{channelID}/conversations/{conversationID}/service-sessions/{serviceSessionID}/rating", s.websiteVisitorRateServiceSession)
	handle("POST /public/website-channels/{channelID}/conversations/{conversationID}/tool-calls/{toolCallID}/decision", s.websiteVisitorDecideToolCall)
	handle("POST /public/website-channels/{channelID}/conversations/{conversationID}/read", s.websiteVisitorMarkConversationRead)
	handle("GET /public/website-channels/{channelID}/help-center", s.websiteVisitorGetHelpCenter)
	handle("GET /public/website-channels/{channelID}/help-center/articles/{articleID}", s.websiteVisitorGetHelpArticle)
	handle("GET /public/website-channels/{channelID}/help-center/search", s.websiteVisitorSearchHelpCenter)
}

// websiteVisitorGetVisitorRealtimeConnection 换取当前访客的短期实时凭据和精确私有频道。
func (s *Service) websiteVisitorGetVisitorRealtimeConnection(writer http.ResponseWriter, request *http.Request) {
	meta, externalID, ok := s.authorizeWebsiteVisitor(writer, request)
	if !ok {
		return
	}
	output, err := s.websiteVisitor.GetVisitorRealtimeConnection(request.Context(), meta, request.PathValue("channelID"), externalID)
	writeWebsiteVisitorResponse(writer, request, output, err)
}

// websiteVisitorListConversations 返回当前渠道身份的客户线程目录，供访客在初始化之后重新发现线程。
func (s *Service) websiteVisitorListConversations(writer http.ResponseWriter, request *http.Request) {
	meta, externalID, ok := s.authorizeWebsiteVisitor(writer, request)
	if !ok {
		return
	}
	output, err := s.websiteVisitor.ListConversations(request.Context(), meta, request.PathValue("channelID"), externalID)
	writeWebsiteVisitorResponse(writer, request, output, err)
}

// websiteVisitorSendTextMessage 持久化网站访客文本消息。
func (s *Service) websiteVisitorSendTextMessage(writer http.ResponseWriter, request *http.Request) {
	meta, externalID, ok := s.authorizeWebsiteVisitor(writer, request)
	if !ok {
		return
	}
	var input appservice.WebsiteVisitorTextMessageInput
	if !bindWebsiteVisitorJSON(writer, request, &input) {
		return
	}
	output, err := s.websiteVisitor.SendTextMessage(request.Context(), meta, request.PathValue("channelID"), externalID, input)
	writeWebsiteVisitorResponse(writer, request, output, err)
}

// websiteVisitorSendAttachmentMessage 持久化网站访客附件消息并激活上传文件。
func (s *Service) websiteVisitorSendAttachmentMessage(writer http.ResponseWriter, request *http.Request) {
	meta, externalID, ok := s.authorizeWebsiteVisitor(writer, request)
	if !ok {
		return
	}
	var input appservice.WebsiteVisitorAttachmentMessageInput
	if !bindWebsiteVisitorJSON(writer, request, &input) {
		return
	}
	output, err := s.websiteVisitor.SendAttachmentMessage(request.Context(), meta, request.PathValue("channelID"), externalID, input)
	writeWebsiteVisitorResponse(writer, request, output, err)
}

// websiteVisitorCreateAttachmentUpload 创建网站访客附件的上传请求。
func (s *Service) websiteVisitorCreateAttachmentUpload(writer http.ResponseWriter, request *http.Request) {
	meta, externalID, ok := s.authorizeWebsiteVisitor(writer, request)
	if !ok {
		return
	}
	var input appservice.WebsiteVisitorUploadInput
	if !bindWebsiteVisitorJSON(writer, request, &input) {
		return
	}
	output, err := s.websiteVisitor.CreateAttachmentUpload(request.Context(), meta, request.PathValue("channelID"), externalID, input)
	writeWebsiteVisitorResponse(writer, request, output, err)
}

// websiteVisitorCompleteAttachmentUpload 核验网站访客上传的附件内容。
func (s *Service) websiteVisitorCompleteAttachmentUpload(writer http.ResponseWriter, request *http.Request) {
	meta, externalID, ok := s.authorizeWebsiteVisitor(writer, request)
	if !ok {
		return
	}
	writeWebsiteVisitorResponse(writer, request, struct{}{}, s.websiteVisitor.CompleteAttachmentUpload(request.Context(), meta, request.PathValue("channelID"), externalID, request.PathValue("fileID")))
}

// websiteVisitorGetMessageAttachment 重新签发网站访客消息附件的预览与下载地址。
func (s *Service) websiteVisitorGetMessageAttachment(writer http.ResponseWriter, request *http.Request) {
	meta, externalID, ok := s.authorizeWebsiteVisitor(writer, request)
	if !ok {
		return
	}
	output, err := s.websiteVisitor.GetMessageAttachment(request.Context(), meta, request.PathValue("channelID"), externalID, request.PathValue("conversationID"), request.PathValue("messageID"))
	writeWebsiteVisitorResponse(writer, request, output, err)
}

// websiteVisitorListMessages 返回网站访客指定客户线程的消息历史。
func (s *Service) websiteVisitorListMessages(writer http.ResponseWriter, request *http.Request) {
	meta, externalID, ok := s.authorizeWebsiteVisitor(writer, request)
	if !ok {
		return
	}
	input, ok := bindVisitorWebsiteVisitorMessageHistoryInputQuery(writer, request)
	if !ok {
		return
	}
	output, err := s.websiteVisitor.ListMessages(request.Context(), meta, request.PathValue("channelID"), externalID, request.PathValue("conversationID"), input)
	writeWebsiteVisitorResponse(writer, request, output, err)
}

// websiteVisitorReportTyping 向企业客服发布网站访客的输入状态。
func (s *Service) websiteVisitorReportTyping(writer http.ResponseWriter, request *http.Request) {
	meta, externalID, ok := s.authorizeWebsiteVisitor(writer, request)
	if !ok {
		return
	}
	var input appservice.WebsiteVisitorTypingInput
	if !bindWebsiteVisitorJSON(writer, request, &input) {
		return
	}
	writeWebsiteVisitorResponse(writer, request, struct{}{}, s.websiteVisitor.ReportTyping(request.Context(), meta, request.PathValue("channelID"), externalID, request.PathValue("conversationID"), input))
}

// websiteVisitorRateServiceSession 保存网站访客对已关闭客服处理周期的评价。
func (s *Service) websiteVisitorRateServiceSession(writer http.ResponseWriter, request *http.Request) {
	meta, externalID, ok := s.authorizeWebsiteVisitor(writer, request)
	if !ok {
		return
	}
	var input appservice.WebsiteVisitorRatingInput
	if !bindWebsiteVisitorJSON(writer, request, &input) {
		return
	}
	output, err := s.websiteVisitor.RateServiceSession(request.Context(), meta, request.PathValue("channelID"), externalID, request.PathValue("conversationID"), request.PathValue("serviceSessionID"), input)
	writeWebsiteVisitorResponse(writer, request, output, err)
}

// websiteVisitorDecideToolCall 由网站访客确认或拒绝 AI 员工在其会话中提交的操作。
func (s *Service) websiteVisitorDecideToolCall(writer http.ResponseWriter, request *http.Request) {
	meta, externalID, ok := s.authorizeWebsiteVisitor(writer, request)
	if !ok {
		return
	}
	var input appservice.WebsiteVisitorToolCallDecisionInput
	if !bindWebsiteVisitorJSON(writer, request, &input) {
		return
	}
	writeWebsiteVisitorResponse(writer, request, struct{}{}, s.websiteVisitor.DecideToolCall(request.Context(), meta, request.PathValue("channelID"), externalID, request.PathValue("conversationID"), request.PathValue("toolCallID"), input))
}

// websiteVisitorMarkConversationRead 记录网站访客在客户线程中已读到的位置。
func (s *Service) websiteVisitorMarkConversationRead(writer http.ResponseWriter, request *http.Request) {
	meta, externalID, ok := s.authorizeWebsiteVisitor(writer, request)
	if !ok {
		return
	}
	var input appservice.WebsiteVisitorReadInput
	if !bindWebsiteVisitorJSON(writer, request, &input) {
		return
	}
	writeWebsiteVisitorResponse(writer, request, struct{}{}, s.websiteVisitor.MarkConversationRead(request.Context(), meta, request.PathValue("channelID"), externalID, request.PathValue("conversationID"), input))
}

// websiteVisitorGetHelpCenter 返回网站渠道帮助中心的文章合集。
func (s *Service) websiteVisitorGetHelpCenter(writer http.ResponseWriter, request *http.Request) {
	meta := s.publicWebsiteVisitorMeta(writer, request)
	output, err := s.websiteVisitor.GetHelpCenter(request.Context(), meta, request.PathValue("channelID"))
	writeWebsiteVisitorResponse(writer, request, output, err)
}

// websiteVisitorGetHelpArticle 返回网站渠道帮助中心的文章详情。
func (s *Service) websiteVisitorGetHelpArticle(writer http.ResponseWriter, request *http.Request) {
	meta := s.publicWebsiteVisitorMeta(writer, request)
	output, err := s.websiteVisitor.GetHelpArticle(request.Context(), meta, request.PathValue("channelID"), request.PathValue("articleID"))
	writeWebsiteVisitorResponse(writer, request, output, err)
}

// websiteVisitorSearchHelpCenter 在网站渠道帮助中心检索访客输入的内容，返回相关文章。
func (s *Service) websiteVisitorSearchHelpCenter(writer http.ResponseWriter, request *http.Request) {
	meta := s.publicWebsiteVisitorMeta(writer, request)
	input, ok := bindVisitorWebsiteVisitorHelpSearchInputQuery(writer, request)
	if !ok {
		return
	}
	output, err := s.websiteVisitor.SearchHelpCenter(request.Context(), meta, request.PathValue("channelID"), input)
	writeWebsiteVisitorResponse(writer, request, output, err)
}

// bindVisitorWebsiteVisitorMessageHistoryInputQuery 从查询参数解析 appservice.WebsiteVisitorMessageHistoryInput，非法时写入校验错误响应。
func bindVisitorWebsiteVisitorMessageHistoryInputQuery(writer http.ResponseWriter, request *http.Request) (appservice.WebsiteVisitorMessageHistoryInput, bool) {
	query := request.URL.Query()
	return appservice.WebsiteVisitorMessageHistoryInput{
		Before: query.Get("before"),
		After:  query.Get("after"),
	}, true
}

// bindVisitorWebsiteVisitorHelpSearchInputQuery 从查询参数解析 appservice.WebsiteVisitorHelpSearchInput，非法时写入校验错误响应。
func bindVisitorWebsiteVisitorHelpSearchInputQuery(writer http.ResponseWriter, request *http.Request) (appservice.WebsiteVisitorHelpSearchInput, bool) {
	query := request.URL.Query()
	return appservice.WebsiteVisitorHelpSearchInput{
		Query: query.Get("q"),
	}, true
}
