// Code generated by appservicegen. DO NOT EDIT.

//go:build !server

package apiproxy

import (
	"context"
	"net/http"
	"net/url"

	"github.com/runforyou-ai/cervi/internal/appservice"
)

// GetDeviceWork 返回本设备的工作水位与待领取运行。
func (b *Backend) GetDeviceWork(ctx context.Context, meta appservice.RequestMeta) (appservice.DeviceWork, error) {
	var output appservice.DeviceWork
	err := b.do(ctx, meta, http.MethodGet, "/devices/current/work", nil, nil, &output)
	return output, err
}

// ReportDeviceLocalAgents 上报本设备上已安装且可用的本机 Agent。
func (b *Backend) ReportDeviceLocalAgents(ctx context.Context, meta appservice.RequestMeta, input appservice.DeviceLocalAgentsInput) error {
	return b.do(ctx, meta, http.MethodPut, "/devices/current/local-agents", nil, input, nil)
}

// ClaimDeviceRun 领取派发给本设备的排队运行并取得租约。
func (b *Backend) ClaimDeviceRun(ctx context.Context, meta appservice.RequestMeta, runID string) (appservice.DeviceRunClaim, error) {
	var output appservice.DeviceRunClaim
	err := b.do(ctx, meta, http.MethodPost, "/agent-runs/"+url.PathEscape(runID)+"/claim", nil, nil, &output)
	return output, err
}

// RenewDeviceRunLease 为本设备持有的运行续租，运行已结束时返回 ended。
func (b *Backend) RenewDeviceRunLease(ctx context.Context, meta appservice.RequestMeta, runID string) (appservice.DeviceRunLease, error) {
	var output appservice.DeviceRunLease
	err := b.do(ctx, meta, http.MethodPost, "/agent-runs/"+url.PathEscape(runID)+"/lease", nil, nil, &output)
	return output, err
}

// PeekDeviceRunInputs 返回本设备持有运行尚未认领的输入信号。
func (b *Backend) PeekDeviceRunInputs(ctx context.Context, meta appservice.RequestMeta, runID string, input appservice.DeviceRunInputPeekInput) (appservice.DeviceRunInputSignals, error) {
	var output appservice.DeviceRunInputSignals
	err := b.do(ctx, meta, http.MethodGet, "/agent-runs/"+url.PathEscape(runID)+"/inputs", encodeDeviceRunInputPeekInputQuery(input), nil, &output)
	return output, err
}

// ClaimDeviceRunInputs 为本设备持有的运行认领输入并返回截至该边界的上下文消息。
func (b *Backend) ClaimDeviceRunInputs(ctx context.Context, meta appservice.RequestMeta, runID string, input appservice.DeviceRunInputClaimInput) (appservice.DeviceRunClaimedInput, error) {
	var output appservice.DeviceRunClaimedInput
	err := b.do(ctx, meta, http.MethodPost, "/agent-runs/"+url.PathEscape(runID)+"/inputs/claim", nil, input, &output)
	return output, err
}

// SearchDeviceRunKnowledge 在本设备持有运行绑定的知识库中检索。
func (b *Backend) SearchDeviceRunKnowledge(ctx context.Context, meta appservice.RequestMeta, runID string, input appservice.DeviceRunKnowledgeSearchInput) (appservice.DeviceRunKnowledgeSearchResult, error) {
	var output appservice.DeviceRunKnowledgeSearchResult
	err := b.do(ctx, meta, http.MethodPost, "/agent-runs/"+url.PathEscape(runID)+"/knowledge/search", nil, input, &output)
	return output, err
}

// GetDeviceRunMemory 返回本设备持有运行所属助理的记忆，有效配置未启用记忆时为空。
func (b *Backend) GetDeviceRunMemory(ctx context.Context, meta appservice.RequestMeta, runID string) (appservice.DeviceRunMemory, error) {
	var output appservice.DeviceRunMemory
	err := b.do(ctx, meta, http.MethodGet, "/agent-runs/"+url.PathEscape(runID)+"/memory", nil, nil, &output)
	return output, err
}

// SearchDeviceRunWeb 用企业配置的搜索服务为本设备持有的运行搜索互联网。
func (b *Backend) SearchDeviceRunWeb(ctx context.Context, meta appservice.RequestMeta, runID string, input appservice.DeviceRunWebSearchInput) (appservice.DeviceRunWebSearchResult, error) {
	var output appservice.DeviceRunWebSearchResult
	err := b.do(ctx, meta, http.MethodPost, "/agent-runs/"+url.PathEscape(runID)+"/web/search", nil, input, &output)
	return output, err
}

// ListDeviceRunMCPTools 列出本设备持有运行绑定的企业 MCP 服务及其工具目录，不可用的服务不列出。
func (b *Backend) ListDeviceRunMCPTools(ctx context.Context, meta appservice.RequestMeta, runID string) (appservice.DeviceRunMCPToolList, error) {
	var output appservice.DeviceRunMCPToolList
	err := b.do(ctx, meta, http.MethodGet, "/agent-runs/"+url.PathEscape(runID)+"/mcp/tools", nil, nil, &output)
	return output, err
}

// CompleteDeviceRun 以成功结果收尾本设备持有的运行。
func (b *Backend) CompleteDeviceRun(ctx context.Context, meta appservice.RequestMeta, runID string, input appservice.DeviceRunResultInput) error {
	return b.do(ctx, meta, http.MethodPost, "/agent-runs/"+url.PathEscape(runID)+"/result", nil, input, nil)
}

// FailDeviceRun 以失败原因收尾派发给本设备的运行。
func (b *Backend) FailDeviceRun(ctx context.Context, meta appservice.RequestMeta, runID string, input appservice.DeviceRunFailureInput) error {
	return b.do(ctx, meta, http.MethodPost, "/agent-runs/"+url.PathEscape(runID)+"/failure", nil, input, nil)
}

// encodeDeviceRunInputPeekInputQuery 将 appservice.DeviceRunInputPeekInput 编码为查询参数。
func encodeDeviceRunInputPeekInputQuery(input appservice.DeviceRunInputPeekInput) url.Values {
	query := url.Values{}
	setPositiveQuery(query, "afterSeq", input.AfterSeq)
	return query
}
