// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AttachedComputer 定义本机为一个账号在一个工作区注册的电脑。
 */
export interface AttachedComputer {
    "workspaceId": string;
    "computerId": string;
}

/**
 * ClientUpdate 是原生端从当前服务器更新客户端的结果。
 */
export interface ClientUpdate {
    "state": ClientUpdateState;

    /**
     * Version 是服务器提供的新版本，只在 State 为 ready 或 available 时有值。
     */
    "version": string;
}

/**
 * ClientUpdateState 表示原生端从当前服务器更新客户端的状态。
 */
export enum ClientUpdateState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ClientUpdateStateUnsupported 表示当前端不能从服务器更新自身。
     */
    ClientUpdateStateUnsupported = "unsupported",

    /**
     * ClientUpdateStateCurrent 表示服务器没有提供比当前客户端更新的版本。
     */
    ClientUpdateStateCurrent = "current",

    /**
     * ClientUpdateStateReady 表示新版本已下载并通过签名校验，重启后生效。
     */
    ClientUpdateStateReady = "ready",

    /**
     * ClientUpdateStateAvailable 表示服务器提供更新的版本，但当前端不能替换自身，需从服务器下载页安装。
     */
    ClientUpdateStateAvailable = "available",
};

/**
 * ComputerAccount 定义一台服务器上的一个账号，本机电脑注册按它分组。
 */
export interface ComputerAccount {
    "serverUrl": string;
    "accountId": string;
}

/**
 * ComputerAttachment 定义前端为一个账号在一个工作区注册这台电脑得到的电脑凭据。
 */
export interface ComputerAttachment {
    "serverUrl": string;
    "accountId": string;
    "workspaceId": string;
    "computerId": string;
    "credential": string;
}

/**
 * ComputerIdentity 定义本机执行器安装标识与上报的电脑名称，前端以之为各工作区注册这台电脑；本机不作为电脑时为空。
 */
export interface ComputerIdentity {
    "installId": string;
    "name": string;
}

/**
 * ConversationWindowInput 定义桌面端打开会话独立窗口的输入，WorkspaceSlug 是会话所在工作区的标识。
 */
export interface ConversationWindowInput {
    "workspaceSlug": string;
    "conversationId": string;
    "title": string;
}

/**
 * ImageFile 定义原生端选择的图片文件。
 */
export interface ImageFile {
    "name": string;
    "contentType": string;
    "dataBase64": string;
}

/**
 * LocalComputer 定义本机在当前工作区的电脑注册状态与运行环境，电脑编号为空表示尚未注册；不作为电脑执行操作的平台运行环境为空。
 */
export interface LocalComputer {
    "computerId": string;
    "toolchain": LocalToolchain | null;
}

/**
 * LocalEnvironment 定义本机为个人 AI 员工提供的运行环境、本地 MCP 服务与技能，未安装的组件版本为空。
 */
export interface LocalEnvironment {
    "toolchain": LocalToolchain;
    "location": string;
    "uvVersion": string;
    "nodeVersion": string;
    "pythonVersion": string;
    "mcpServers": LocalMCPServer[] | null;
    "skills": LocalSkill[] | null;
}

/**
 * LocalMCPServer 定义这台电脑上负责人的个人 AI 员工共用的一个本地 MCP 服务：本地进程给出启动命令与参数，SSE 与 Streamable HTTP 服务给出地址。
 */
export interface LocalMCPServer {
    "name": string;
    "type": LocalMCPServerType;
    "command": string;
    "args": string[] | null;
    "url": string;
}

/**
 * LocalMCPServerInput 定义添加到这台电脑的本地 MCP 服务：本地进程给出启动命令、参数与环境变量，SSE 与 Streamable HTTP 服务给出地址与请求头。
 */
export interface LocalMCPServerInput {
    "name": string;
    "type": LocalMCPServerType;
    "command": string;
    "args": string[] | null;
    "env": { [_ in string]?: string } | null;
    "url": string;
    "headers": { [_ in string]?: string } | null;
}

/**
 * LocalMCPServerType 定义本地 MCP 服务的连接方式。
 */
export enum LocalMCPServerType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * LocalMCPServerTypeStdio 表示启动本地进程并经标准输入输出通信。
     */
    LocalMCPServerTypeStdio = "stdio",

    /**
     * LocalMCPServerTypeSSE 表示连接 SSE 服务。
     */
    LocalMCPServerTypeSSE = "sse",

    /**
     * LocalMCPServerTypeHTTP 表示连接 Streamable HTTP 服务。
     */
    LocalMCPServerTypeHTTP = "http",
};

/**
 * LocalSkill 定义这台电脑上负责人的个人 AI 员工共用的一个技能及其所在文件夹。
 */
export interface LocalSkill {
    "name": string;
    "description": string;
    "source": LocalSkillSource;
    "location": string;
}

/**
 * LocalSkillInstallInput 定义要安装到这台电脑的技能来源，来源含多个技能时按 Name 选择。
 */
export interface LocalSkillInstallInput {
    "source": string;
    "name": string;
}

/**
 * LocalSkillSource 定义技能所在目录的来源。
 */
export enum LocalSkillSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * LocalSkillSourceManaged 表示个人 AI 员工安装的技能，可以删除。
     */
    LocalSkillSourceManaged = "managed",

    /**
     * LocalSkillSourceAgents 表示其他 AI 工具安装在跨工具共用目录中的技能。
     */
    LocalSkillSourceAgents = "agents",

    /**
     * LocalSkillSourceClaude 表示 Claude 目录中的技能。
     */
    LocalSkillSourceClaude = "claude",
};

/**
 * LocalToolchain 定义本机 Agent 运行环境的准备状态，失败原因只在失败状态下非空，Updating 表示正在按用户请求更新。
 */
export interface LocalToolchain {
    "state": LocalToolchainState;
    "failure": LocalToolchainFailure | null;
    "updating": boolean;
}

/**
 * LocalToolchainFailure 定义运行环境准备失败的原因。
 */
export enum LocalToolchainFailure {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * LocalToolchainFailureDownload 表示无法从下载源取得安装文件。
     */
    LocalToolchainFailureDownload = "download",

    /**
     * LocalToolchainFailureVerify 表示下载的安装文件校验失败。
     */
    LocalToolchainFailureVerify = "verify",

    /**
     * LocalToolchainFailureInstall 表示在本机安装失败。
     */
    LocalToolchainFailureInstall = "install",
};

/**
 * LocalToolchainState 定义本机 Agent 运行环境的准备状态。
 */
export enum LocalToolchainState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * LocalToolchainStatePreparing 表示运行环境正在准备或尚未开始准备。
     */
    LocalToolchainStatePreparing = "preparing",

    /**
     * LocalToolchainStateReady 表示已有可用的运行环境。
     */
    LocalToolchainStateReady = "ready",

    /**
     * LocalToolchainStateFailed 表示最近一次准备失败，等待自动重试。
     */
    LocalToolchainStateFailed = "failed",

    /**
     * LocalToolchainStateUninstalled 表示用户已卸载运行环境，重新安装前不自动安装。
     */
    LocalToolchainStateUninstalled = "uninstalled",
};

/**
 * LocalToolchainUpdate 定义更新本机运行环境的结果，Updated 表示有组件换了版本。
 */
export interface LocalToolchainUpdate {
    "updated": boolean;
}

/**
 * MessageNotificationInput 定义当前设备的新消息通知内容；Path 是点击通知后打开的工作区页面地址（`/w/<工作区标识>/...`），为空时只把应用带到前台。
 */
export interface MessageNotificationInput {
    "id": string;
    "title": string;
    "body": string;
    "soundEnabled": boolean;
    "path": string;
}

/**
 * NotificationPermissionStatus 表示当前设备的系统通知授权状态。
 */
export enum NotificationPermissionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NotificationPermissionStatusPrompt = "prompt",
    NotificationPermissionStatusGranted = "granted",
    NotificationPermissionStatusDenied = "denied",
    NotificationPermissionStatusUnsupported = "unsupported",
};

/**
 * TextFileInput 定义原生端保存的文本文件：Name 为建议文件名，Content 为 UTF-8 文本内容。
 */
export interface TextFileInput {
    "name": string;
    "content": string;
}

/**
 * UnreadIndicatorState 定义未读数量和托盘提醒条件。
 */
export interface UnreadIndicatorState {
    "count": number;
    "attentionEnabled": boolean;
    "attentionPending": boolean;
}
