// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 是前端经 Wails 绑定调用的本机能力；业务数据由前端直接请求服务端。本机能力的错误文案使用界面最近同步的语言，结果中的切片均为数组。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddLocalMCPServer 试启动并添加这台电脑上的本地 MCP 服务，同名服务被替换。
 */
export function AddLocalMCPServer(input: $models.LocalMCPServerInput): $CancellablePromise<void> {
    return $Call.ByID(1317508063, input);
}

/**
 * AttachComputer 保存前端为一个工作区注册得到的电脑凭据，并以之连接服务端执行派发给这台电脑的操作。
 */
export function AttachComputer(attachment: $models.ComputerAttachment): $CancellablePromise<void> {
    return $Call.ByID(2492219550, attachment);
}

/**
 * CheckNotificationPermission 返回当前设备的系统通知授权状态。
 */
export function CheckNotificationPermission(): $CancellablePromise<$models.NotificationPermissionStatus> {
    return $Call.ByID(929975002);
}

/**
 * CloseConversationWindows 关闭全部会话独立窗口，登录会话变化时由主窗口调用。
 */
export function CloseConversationWindows(): $CancellablePromise<void> {
    return $Call.ByID(1938425030);
}

/**
 * CurrentComputer 返回本机在指定工作区为指定账号注册的电脑与运行环境的准备状态；本机不作为电脑时返回空电脑。
 */
export function CurrentComputer(account: $models.ComputerAccount, workspaceID: string): $CancellablePromise<$models.LocalComputer> {
    return $Call.ByID(3458045150, account, workspaceID);
}

/**
 * DetachComputers 删除本机在指定服务器上为指定账号注册、但工作区不在 keepWorkspaceIDs 中的电脑。
 */
export function DetachComputers(account: $models.ComputerAccount, keepWorkspaceIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(468682941, account, keepWorkspaceIDs);
}

/**
 * GetComputerIdentity 返回本机执行器安装标识与电脑名称；本机不作为电脑时返回空标识。
 */
export function GetComputerIdentity(): $CancellablePromise<$models.ComputerIdentity> {
    return $Call.ByID(3240548625);
}

/**
 * GetLocalEnvironment 返回本机为个人 AI 员工提供的运行环境、本地 MCP 服务与技能。
 */
export function GetLocalEnvironment(): $CancellablePromise<$models.LocalEnvironment> {
    return $Call.ByID(1515631054);
}

/**
 * InstallLocalSkill 从来源把技能安装到这台电脑，同名技能被替换。
 */
export function InstallLocalSkill(input: $models.LocalSkillInstallInput): $CancellablePromise<void> {
    return $Call.ByID(2077818013, input);
}

/**
 * InstallLocalToolchain 重新安装已卸载的本机运行环境。
 */
export function InstallLocalToolchain(): $CancellablePromise<void> {
    return $Call.ByID(808439767);
}

/**
 * ListAttachedComputers 返回本机在指定服务器上为指定账号注册的各工作区电脑。
 */
export function ListAttachedComputers(account: $models.ComputerAccount): $CancellablePromise<$models.AttachedComputer[] | null> {
    return $Call.ByID(4199210652, account);
}

/**
 * OpenConversationWindow 在独立窗口打开指定会话，同一会话已打开时聚焦现有窗口。
 */
export function OpenConversationWindow(input: $models.ConversationWindowInput): $CancellablePromise<void> {
    return $Call.ByID(3385454773, input);
}

/**
 * OpenLocalToolchainFolder 在系统文件管理器中打开本机运行环境的安装位置。
 */
export function OpenLocalToolchainFolder(): $CancellablePromise<void> {
    return $Call.ByID(713442496);
}

/**
 * PrepareClientUpdate 检查服务器提供的客户端版本，较新时下载更新包并校验签名；当前端不能从服务器更新时返回 unsupported。
 */
export function PrepareClientUpdate(serverURL: string): $CancellablePromise<$models.ClientUpdate> {
    return $Call.ByID(3331300007, serverURL);
}

/**
 * RemoveLocalMCPServer 删除这台电脑上的本地 MCP 服务。
 */
export function RemoveLocalMCPServer(name: string): $CancellablePromise<void> {
    return $Call.ByID(3410947228, name);
}

/**
 * RemoveLocalSkill 删除 AI 员工安装在这台电脑上的技能。
 */
export function RemoveLocalSkill(name: string): $CancellablePromise<void> {
    return $Call.ByID(3998100674, name);
}

/**
 * RequestNotificationPermission 申请系统通知授权并返回授权状态。
 */
export function RequestNotificationPermission(): $CancellablePromise<$models.NotificationPermissionStatus> {
    return $Call.ByID(3488830987);
}

/**
 * RestartClientUpdate 退出应用并以已准备好的新版本重新启动。
 */
export function RestartClientUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3529909067);
}

/**
 * SaveTextFile 让用户选择保存位置并写入文本文件，用户取消时返回 false。
 */
export function SaveTextFile(input: $models.TextFileInput): $CancellablePromise<boolean> {
    return $Call.ByID(101974738, input);
}

/**
 * SelectImage 打开系统文件对话框选择并读取图片，用户取消时返回空文件。
 */
export function SelectImage(): $CancellablePromise<$models.ImageFile> {
    return $Call.ByID(4097832083);
}

/**
 * SendMessageNotification 投递一条新消息通知。
 */
export function SendMessageNotification(input: $models.MessageNotificationInput): $CancellablePromise<void> {
    return $Call.ByID(2805213700, input);
}

/**
 * SetLocale 同步界面语言到托盘、应用菜单与本机能力的错误文案。
 */
export function SetLocale(locale: string): $CancellablePromise<void> {
    return $Call.ByID(2081163328, locale);
}

/**
 * TakeOpenedNotificationPath 返回并清除最近一次被点击的通知要打开的页面地址，没有时返回空串。
 */
export function TakeOpenedNotificationPath(): $CancellablePromise<string> {
    return $Call.ByID(1228524800);
}

/**
 * TakeOpenedServerLink 返回并清除最近一次唤起应用的连接链接携带的部署地址，没有时返回空串。
 */
export function TakeOpenedServerLink(): $CancellablePromise<string> {
    return $Call.ByID(1075331063);
}

/**
 * UninstallLocalToolchain 卸载本机运行环境，手动重新安装前保持未安装。
 */
export function UninstallLocalToolchain(): $CancellablePromise<void> {
    return $Call.ByID(1998230182);
}

/**
 * UpdateLocalToolchain 把本机运行环境更新到下载源的最新版本。
 */
export function UpdateLocalToolchain(): $CancellablePromise<$models.LocalToolchainUpdate> {
    return $Call.ByID(971790065);
}

/**
 * UpdateUnreadIndicator 同步当前设备的未读数和托盘提醒状态。
 */
export function UpdateUnreadIndicator(state: $models.UnreadIndicatorState): $CancellablePromise<void> {
    return $Call.ByID(1566071117, state);
}
