// i18nkeygen 读取 internal/i18n 下应用语言的中英文词条文件，校验两者词条键一致、对客语言词条键均为应用词条键，并生成 keys_gen.go 中的文案键常量。
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"go/token"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// appLocaleFiles 是应用语言的完整词条文件。
var appLocaleFiles = []string{"locales/zh-CN.json", "locales/en-US.json"}

// wordForms 是常量名中按固定写法输出的词，其余词首字母大写。
var wordForms = map[string]string{
	"aes":     "AES",
	"ai":      "AI",
	"api":     "API",
	"builtin": "BuiltIn",
	"http":    "HTTP",
	"id":      "ID",
	"ids":     "IDs",
	"ip":      "IP",
	"mcp":     "MCP",
	"qa":      "QA",
	"sdk":     "SDK",
	"smtp":    "SMTP",
	"url":     "URL",
	"wecom":   "WeCom",
}

// main 在当前目录（internal/i18n）生成文案键常量文件。
func main() {
	if err := run("."); err != nil {
		fmt.Fprintln(os.Stderr, "i18nkeygen:", err)
		os.Exit(1)
	}
}

// run 读取并校验 dir 下的词条文件，内容变化时写出 keys_gen.go。
func run(dir string) error {
	var keys []string
	for index, path := range appLocaleFiles {
		fileKeys, err := readKeys(filepath.Join(dir, path))
		if err != nil {
			return err
		}
		if index == 0 {
			keys = fileKeys
			continue
		}
		if !slices.Equal(keys, fileKeys) {
			return fmt.Errorf("%s 与 %s 的词条键不一致", path, appLocaleFiles[0])
		}
	}
	customerFiles, err := filepath.Glob(filepath.Join(dir, "locales", "customer", "*.json"))
	if err != nil {
		return err
	}
	for _, path := range customerFiles {
		fileKeys, err := readKeys(path)
		if err != nil {
			return err
		}
		for _, key := range fileKeys {
			if _, found := slices.BinarySearch(keys, key); !found {
				return fmt.Errorf("%s 的词条键 %q 不在应用词条中", path, key)
			}
		}
	}
	var source bytes.Buffer
	source.WriteString("// Code generated by i18nkeygen; DO NOT EDIT.\n\npackage i18n\n\n// 应用词条文件中的全部文案键。\nconst (\n")
	names := make(map[string]string, len(keys))
	for _, key := range keys {
		name := constName(key)
		if !token.IsIdentifier(name) || !token.IsExported(name) {
			return fmt.Errorf("词条键 %q 无法生成常量名", key)
		}
		if other, exists := names[name]; exists {
			return fmt.Errorf("词条键 %q 与 %q 生成相同的常量名 %s", key, other, name)
		}
		names[name] = key
		fmt.Fprintf(&source, "\t%s Key = %q\n", name, key)
	}
	source.WriteString(")\n")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return err
	}
	path := filepath.Join(dir, "keys_gen.go")
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, formatted) {
		return nil
	}
	return os.WriteFile(path, formatted, 0o644)
}

// readKeys 返回词条文件中按字典序排列的词条键。
func readKeys(path string) ([]string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var messages map[string]string
	if err := json.Unmarshal(content, &messages); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return slices.Sorted(maps.Keys(messages)), nil
}

// constName 把以点号和下划线分词的词条键转为驼峰常量名。
func constName(key string) string {
	var name strings.Builder
	for word := range strings.FieldsFuncSeq(key, func(r rune) bool { return r == '.' || r == '_' }) {
		if form, ok := wordForms[word]; ok {
			name.WriteString(form)
			continue
		}
		name.WriteString(strings.ToUpper(word[:1]) + word[1:])
	}
	return name.String()
}
