// Code generated by appservicegen. DO NOT EDIT.

package appservice

import "context"

// InstallationStatus 返回部署名称、首次安装状态、是否开放注册和产品品牌。
func (s *Service) InstallationStatus(ctx context.Context, meta RequestMeta) (InstallationStatus, error) {
	return WithNormalizedSlices(s.backend.InstallationStatus(ctx, meta))
}

// GetProductDocPage 返回当前部署可见的产品文档页面正文，供应用内帮助显示。
func (s *Service) GetProductDocPage(ctx context.Context, meta RequestMeta, input ProductDocPageInput) (ProductDocPage, error) {
	return WithNormalizedSlices(s.backend.GetProductDocPage(ctx, meta, input))
}

// Logout 退出当前登录会话。
func (s *Service) Logout(ctx context.Context, meta RequestMeta) error {
	return s.backend.Logout(ctx, meta)
}

// LoadAccount 返回当前登录账号。
func (s *Service) LoadAccount(ctx context.Context, meta RequestMeta) (Account, error) {
	return WithNormalizedSlices(s.backend.LoadAccount(ctx, meta))
}

// ListWorkspaces 返回当前账号作为有效成员可进入的工作区，以及当前账号能否再创建工作区。
func (s *Service) ListWorkspaces(ctx context.Context, meta RequestMeta) (WorkspaceList, error) {
	return WithNormalizedSlices(s.backend.ListWorkspaces(ctx, meta))
}

// ListWorkspaceAttention 返回当前账号在各工作区的提醒数量，工作区切换器与应用角标据此提示其他工作区的未读。
func (s *Service) ListWorkspaceAttention(ctx context.Context, meta RequestMeta) (WorkspaceAttentionList, error) {
	return WithNormalizedSlices(s.backend.ListWorkspaceAttention(ctx, meta))
}

// CreateWorkspace 创建工作区，当前账号成为首位管理员成员。
func (s *Service) CreateWorkspace(ctx context.Context, meta RequestMeta, input WorkspaceInput) (Workspace, error) {
	return WithNormalizedSlices(s.backend.CreateWorkspace(ctx, meta, input))
}

// UpdateProfile 修改当前成员的头像和姓名，以及所属账号的邮箱。
func (s *Service) UpdateProfile(ctx context.Context, meta RequestMeta, input ProfileInput) (CurrentUser, error) {
	return WithNormalizedSlices(s.backend.UpdateProfile(ctx, meta, input))
}

// CreateFileUpload 创建文件上传请求。
func (s *Service) CreateFileUpload(ctx context.Context, meta RequestMeta, input FileUploadInput) (FileUpload, error) {
	return WithNormalizedSlices(s.backend.CreateFileUpload(ctx, meta, input))
}

// CompleteFileUpload 核验并完成文件上传。
func (s *Service) CompleteFileUpload(ctx context.Context, meta RequestMeta, fileID string) (File, error) {
	return WithNormalizedSlices(s.backend.CompleteFileUpload(ctx, meta, fileID))
}

// CreateFilePartUpload 创建一个分片的直传请求。
func (s *Service) CreateFilePartUpload(ctx context.Context, meta RequestMeta, fileID string, input FilePartUploadInput) (FileUploadRequest, error) {
	return WithNormalizedSlices(s.backend.CreateFilePartUpload(ctx, meta, fileID, input))
}

// CancelFileUpload 将未发送的临时文件交给清理任务。
func (s *Service) CancelFileUpload(ctx context.Context, meta RequestMeta, fileID string) error {
	return s.backend.CancelFileUpload(ctx, meta, fileID)
}

// SendAttachmentMessage 发送已上传的单聊、群聊或 AI 聊天附件消息，首发时创建会话。
func (s *Service) SendAttachmentMessage(ctx context.Context, meta RequestMeta, input AttachmentMessageInput) (AttachmentMessageResult, error) {
	return WithNormalizedSlices(s.backend.SendAttachmentMessage(ctx, meta, input))
}

// GetAttachmentDownload 签发当前成员可见消息附件的下载地址。
func (s *Service) GetAttachmentDownload(ctx context.Context, meta RequestMeta, conversationID string, messageID string) (FileDownload, error) {
	return WithNormalizedSlices(s.backend.GetAttachmentDownload(ctx, meta, conversationID, messageID))
}

// ChangePassword 核验当前账号的密码并保存新密码。
func (s *Service) ChangePassword(ctx context.Context, meta RequestMeta, input ChangePasswordInput) error {
	return s.backend.ChangePassword(ctx, meta, input)
}

// UpdateUserWorkStatus 保存当前用户主动设置的工作状态。
func (s *Service) UpdateUserWorkStatus(ctx context.Context, meta RequestMeta, input UserWorkStatusInput) (CurrentUser, error) {
	return WithNormalizedSlices(s.backend.UpdateUserWorkStatus(ctx, meta, input))
}

// LoadInbox 返回当前用户的统一收件箱。
func (s *Service) LoadInbox(ctx context.Context, meta RequestMeta, input LoadInboxInput) (Inbox, error) {
	return WithNormalizedSlices(s.backend.LoadInbox(ctx, meta, input))
}

// GetInboxContext 返回会话锚点的当前资格和原位置邻域。
func (s *Service) GetInboxContext(ctx context.Context, meta RequestMeta, input InboxContextInput) (InboxContext, error) {
	return WithNormalizedSlices(s.backend.GetInboxContext(ctx, meta, input))
}

// ReadInboxWindow 重读已加载双向边界之间的完整列表范围。
func (s *Service) ReadInboxWindow(ctx context.Context, meta RequestMeta, input InboxWindowInput) (InboxWindow, error) {
	return WithNormalizedSlices(s.backend.ReadInboxWindow(ctx, meta, input))
}

// GetRequesterProfile 返回服务会话发起人的资料；发起人是客户时给出客户身份与当前周期访客上下文。
func (s *Service) GetRequesterProfile(ctx context.Context, meta RequestMeta, conversationID string) (RequesterProfile, error) {
	return WithNormalizedSlices(s.backend.GetRequesterProfile(ctx, meta, conversationID))
}

// ListServiceBusinessQueries 返回服务会话当前周期内 AI 员工查询业务系统的记录。
func (s *Service) ListServiceBusinessQueries(ctx context.Context, meta RequestMeta, conversationID string) (ServiceBusinessQueryList, error) {
	return WithNormalizedSlices(s.backend.ListServiceBusinessQueries(ctx, meta, conversationID))
}

// GetServiceSummaries 返回服务会话当前周期的交接摘要与同一发起人已关闭周期的小结。
func (s *Service) GetServiceSummaries(ctx context.Context, meta RequestMeta, conversationID string) (ServiceSummaries, error) {
	return WithNormalizedSlices(s.backend.GetServiceSummaries(ctx, meta, conversationID))
}

// UpdateServiceSessionSummary 修改已关闭服务周期的小结、是否解决与咨询分类。
func (s *Service) UpdateServiceSessionSummary(ctx context.Context, meta RequestMeta, serviceSessionID string, input ServiceSessionSummaryInput) (ServiceSessionSummary, error) {
	return WithNormalizedSlices(s.backend.UpdateServiceSessionSummary(ctx, meta, serviceSessionID, input))
}

// GetInboxConversation 返回当前用户有权阅读的独立会话摘要。
func (s *Service) GetInboxConversation(ctx context.Context, meta RequestMeta, conversationID string) (InboxConversation, error) {
	return WithNormalizedSlices(s.backend.GetInboxConversation(ctx, meta, conversationID))
}

// ReadInboxConversations 按 ID 批量返回会话摘要及当前筛选资格。
func (s *Service) ReadInboxConversations(ctx context.Context, meta RequestMeta, input ReadInboxConversationsInput) (InboxConversationResults, error) {
	return WithNormalizedSlices(s.backend.ReadInboxConversations(ctx, meta, input))
}

// ReadConversationAttention 返回会话摘要及已知消息之后计入本人提醒的未读消息，提醒口径与应用角标一致。
func (s *Service) ReadConversationAttention(ctx context.Context, meta RequestMeta, conversationID string, input ConversationAttentionInput) (ConversationAttention, error) {
	return WithNormalizedSlices(s.backend.ReadConversationAttention(ctx, meta, conversationID, input))
}

// SearchInbox 按范围检索会话名称、消息正文与附件文件名、成员和外部联系人。
func (s *Service) SearchInbox(ctx context.Context, meta RequestMeta, input InboxSearchInput) (InboxSearchResult, error) {
	return WithNormalizedSlices(s.backend.SearchInbox(ctx, meta, input))
}

// ListServiceAssignees 返回可接待服务会话的有效真人和 AI 员工。
func (s *Service) ListServiceAssignees(ctx context.Context, meta RequestMeta) (ServiceAssigneeList, error) {
	return WithNormalizedSlices(s.backend.ListServiceAssignees(ctx, meta))
}

// ListServiceQueueTeams 返回可作为客服队列的团队，本人所在团队排在前面。
func (s *Service) ListServiceQueueTeams(ctx context.Context, meta RequestMeta) (ServiceQueueTeamList, error) {
	return WithNormalizedSlices(s.backend.ListServiceQueueTeams(ctx, meta))
}

// ListInboxChannels 返回收件箱渠道筛选候选，含已停用渠道。
func (s *Service) ListInboxChannels(ctx context.Context, meta RequestMeta) (InboxChannelList, error) {
	return WithNormalizedSlices(s.backend.ListInboxChannels(ctx, meta))
}

// GetSyncHeads 返回当前用户可见会话与身份资料的同步探针值。
func (s *Service) GetSyncHeads(ctx context.Context, meta RequestMeta) (SyncHeads, error) {
	return WithNormalizedSlices(s.backend.GetSyncHeads(ctx, meta))
}

// ListConversationMessages 返回成员可见的会话消息。
func (s *Service) ListConversationMessages(ctx context.Context, meta RequestMeta, conversationID string, input ConversationMessageListInput) (ConversationMessageList, error) {
	return WithNormalizedSlices(s.backend.ListConversationMessages(ctx, meta, conversationID, input))
}

// ReadConversationMessageWindow 重读已加载首尾游标之间的完整消息范围。
func (s *Service) ReadConversationMessageWindow(ctx context.Context, meta RequestMeta, conversationID string, input ConversationMessageWindowInput) (ConversationMessageList, error) {
	return WithNormalizedSlices(s.backend.ReadConversationMessageWindow(ctx, meta, conversationID, input))
}

// GetConversationMessageContext 返回目标消息及其前后上下文。
func (s *Service) GetConversationMessageContext(ctx context.Context, meta RequestMeta, conversationID string, messageID string) (ConversationMessageList, error) {
	return WithNormalizedSlices(s.backend.GetConversationMessageContext(ctx, meta, conversationID, messageID))
}

// GetConversationNavigationState 返回群聊提及进度和最新可见消息。
func (s *Service) GetConversationNavigationState(ctx context.Context, meta RequestMeta, conversationID string) (ConversationNavigationState, error) {
	return WithNormalizedSlices(s.backend.GetConversationNavigationState(ctx, meta, conversationID))
}

// ListPendingConversationMentions 返回本轮待查看提及目标。
func (s *Service) ListPendingConversationMentions(ctx context.Context, meta RequestMeta, conversationID string) (PendingConversationMentions, error) {
	return WithNormalizedSlices(s.backend.ListPendingConversationMentions(ctx, meta, conversationID))
}

// MarkConversationMentionReviewed 确认已查看的群聊提及。
func (s *Service) MarkConversationMentionReviewed(ctx context.Context, meta RequestMeta, conversationID string, input MarkConversationMentionReviewedInput) (ConversationMentionReview, error) {
	return WithNormalizedSlices(s.backend.MarkConversationMentionReviewed(ctx, meta, conversationID, input))
}

// MarkConversationRead 单调推进当前用户的会话已读水位。
func (s *Service) MarkConversationRead(ctx context.Context, meta RequestMeta, conversationID string, input MarkConversationReadInput) (ConversationReadState, error) {
	return WithNormalizedSlices(s.backend.MarkConversationRead(ctx, meta, conversationID, input))
}

// ReportConversationTyping 发布当前用户的输入状态：单聊与群聊发给其他真人成员，网站渠道客户会话发给该线程访客。
func (s *Service) ReportConversationTyping(ctx context.Context, meta RequestMeta, conversationID string, input ConversationTypingInput) error {
	return s.backend.ReportConversationTyping(ctx, meta, conversationID, input)
}

// UpdateConversationUnreadMark 保存当前用户独立于阅读水位的未读标记。
func (s *Service) UpdateConversationUnreadMark(ctx context.Context, meta RequestMeta, conversationID string, input ConversationUnreadMarkInput) error {
	return s.backend.UpdateConversationUnreadMark(ctx, meta, conversationID, input)
}

// UpdateConversationPin 保存当前用户的会话置顶事实与置顶顺序。
func (s *Service) UpdateConversationPin(ctx context.Context, meta RequestMeta, conversationID string, input ConversationPinInput) (ConversationPinState, error) {
	return WithNormalizedSlices(s.backend.UpdateConversationPin(ctx, meta, conversationID, input))
}

// ListArchivedConversations 按最近活动倒序返回当前用户已归档的群聊、单聊与 AI 聊天。
func (s *Service) ListArchivedConversations(ctx context.Context, meta RequestMeta, input ArchivedConversationListInput) (ArchivedConversationList, error) {
	return WithNormalizedSlices(s.backend.ListArchivedConversations(ctx, meta, input))
}

// UpdateConversationArchive 保存当前用户对群聊、单聊或 AI 聊天的归档状态。
func (s *Service) UpdateConversationArchive(ctx context.Context, meta RequestMeta, conversationID string, input ConversationArchiveInput) error {
	return s.backend.UpdateConversationArchive(ctx, meta, conversationID, input)
}

// UpdateConversationNotificationSettings 保存当前用户的原生会话提醒设置。
func (s *Service) UpdateConversationNotificationSettings(ctx context.Context, meta RequestMeta, conversationID string, input ConversationNotificationSettingsInput) (ConversationNotificationSettings, error) {
	return WithNormalizedSlices(s.backend.UpdateConversationNotificationSettings(ctx, meta, conversationID, input))
}

// SendServiceTextMessage 在服务会话中发送回复或内部备注。
func (s *Service) SendServiceTextMessage(ctx context.Context, meta RequestMeta, conversationID string, input ServiceTextMessageInput) (ConversationMessage, error) {
	return WithNormalizedSlices(s.backend.SendServiceTextMessage(ctx, meta, conversationID, input))
}

// SendServiceAttachmentMessage 在服务会话中发送附件回复。
func (s *Service) SendServiceAttachmentMessage(ctx context.Context, meta RequestMeta, conversationID string, input ServiceAttachmentMessageInput) (ConversationMessage, error) {
	return WithNormalizedSlices(s.backend.SendServiceAttachmentMessage(ctx, meta, conversationID, input))
}

// GetConversationTranslation 返回当前成员在客户会话中的翻译状态。
func (s *Service) GetConversationTranslation(ctx context.Context, meta RequestMeta, conversationID string) (ConversationTranslation, error) {
	return WithNormalizedSlices(s.backend.GetConversationTranslation(ctx, meta, conversationID))
}

// TranslateConversationMessages 返回客户会话中指定对客消息面向当前成员语言的译文，尚无译文的消息即时翻译。
func (s *Service) TranslateConversationMessages(ctx context.Context, meta RequestMeta, conversationID string, input TranslateConversationMessagesInput) (ConversationMessageTranslationList, error) {
	return WithNormalizedSlices(s.backend.TranslateConversationMessages(ctx, meta, conversationID, input))
}

// UpdateCustomerReplyLanguage 锁定或解除客户会话的对客回复语言。
func (s *Service) UpdateCustomerReplyLanguage(ctx context.Context, meta RequestMeta, conversationID string, input CustomerReplyLanguageInput) (ConversationTranslation, error) {
	return WithNormalizedSlices(s.backend.UpdateCustomerReplyLanguage(ctx, meta, conversationID, input))
}

// PreviewCustomerReplyTranslation 把客服回复译为客户语言并回译为客服语言，供发送前核对。
func (s *Service) PreviewCustomerReplyTranslation(ctx context.Context, meta RequestMeta, conversationID string, input CustomerReplyTranslationInput) (CustomerReplyTranslationPreview, error) {
	return WithNormalizedSlices(s.backend.PreviewCustomerReplyTranslation(ctx, meta, conversationID, input))
}

// ListServiceReplyAgents 返回可用于 AI 写回复的 AI 员工。
func (s *Service) ListServiceReplyAgents(ctx context.Context, meta RequestMeta) (ServiceReplyAgentList, error) {
	return WithNormalizedSlices(s.backend.ListServiceReplyAgents(ctx, meta))
}

// GenerateServiceReplySuggestions 使用 AI 员工为服务会话生成回复候选。
func (s *Service) GenerateServiceReplySuggestions(ctx context.Context, meta RequestMeta, conversationID string, input ServiceReplySuggestionsInput) (ServiceReplySuggestions, error) {
	return WithNormalizedSlices(s.backend.GenerateServiceReplySuggestions(ctx, meta, conversationID, input))
}

// ListServiceCopilotThreads 返回服务会话的全部 Copilot 线程。
func (s *Service) ListServiceCopilotThreads(ctx context.Context, meta RequestMeta, conversationID string) (ServiceCopilotThreadList, error) {
	return WithNormalizedSlices(s.backend.ListServiceCopilotThreads(ctx, meta, conversationID))
}

// SendFirstServiceCopilotMessage 以首条提问创建服务会话的 Copilot 线程。
func (s *Service) SendFirstServiceCopilotMessage(ctx context.Context, meta RequestMeta, conversationID string, input FirstServiceCopilotMessageInput) (FirstServiceCopilotMessageResult, error) {
	return WithNormalizedSlices(s.backend.SendFirstServiceCopilotMessage(ctx, meta, conversationID, input))
}

// SendServiceCopilotTextMessage 向 Copilot 线程发送提问。
func (s *Service) SendServiceCopilotTextMessage(ctx context.Context, meta RequestMeta, threadID string, input ServiceCopilotTextMessageInput) (ConversationMessage, error) {
	return WithNormalizedSlices(s.backend.SendServiceCopilotTextMessage(ctx, meta, threadID, input))
}

// StopServiceCopilotReply 停止 Copilot 线程中指定的回复并返回实际运行状态。
func (s *Service) StopServiceCopilotReply(ctx context.Context, meta RequestMeta, threadID string, runID string) (AgentRunStatus, error) {
	return WithNormalizedSlices(s.backend.StopServiceCopilotReply(ctx, meta, threadID, runID))
}

// ResolveCustomerMessageDelivery 人工处理失败或待确认的投递。
func (s *Service) ResolveCustomerMessageDelivery(ctx context.Context, meta RequestMeta, conversationID string, deliveryID string, input CustomerDeliveryResolveInput) error {
	return s.backend.ResolveCustomerMessageDelivery(ctx, meta, conversationID, deliveryID, input)
}

// ClaimServiceSession 领取或接管服务会话的当前周期。
func (s *Service) ClaimServiceSession(ctx context.Context, meta RequestMeta, conversationID string) (ServiceSession, error) {
	return WithNormalizedSlices(s.backend.ClaimServiceSession(ctx, meta, conversationID))
}

// TransferServiceSession 把当前负责的处理周期转给成员、团队队列或公共队列。
func (s *Service) TransferServiceSession(ctx context.Context, meta RequestMeta, conversationID string, input TransferServiceSessionInput) (ServiceSession, error) {
	return WithNormalizedSlices(s.backend.TransferServiceSession(ctx, meta, conversationID, input))
}

// CloseServiceSession 关闭服务会话的当前周期。
func (s *Service) CloseServiceSession(ctx context.Context, meta RequestMeta, conversationID string) (ServiceSession, error) {
	return WithNormalizedSlices(s.backend.CloseServiceSession(ctx, meta, conversationID))
}

// ReopenServiceSession 重新打开服务会话的当前周期并分配给当前身份。
func (s *Service) ReopenServiceSession(ctx context.Context, meta RequestMeta, conversationID string) (ServiceSession, error) {
	return WithNormalizedSlices(s.backend.ReopenServiceSession(ctx, meta, conversationID))
}

// SendFirstDirectTextMessage 向目标身份发送首条单聊消息并按需创建长期会话。
func (s *Service) SendFirstDirectTextMessage(ctx context.Context, meta RequestMeta, input FirstDirectTextMessageInput) (FirstDirectTextMessageResult, error) {
	return WithNormalizedSlices(s.backend.SendFirstDirectTextMessage(ctx, meta, input))
}

// SendFirstAgentTextMessage 在首次发送时创建独立 AI 聊天。
func (s *Service) SendFirstAgentTextMessage(ctx context.Context, meta RequestMeta, input FirstAgentTextMessageInput) (FirstAgentTextMessageResult, error) {
	return WithNormalizedSlices(s.backend.SendFirstAgentTextMessage(ctx, meta, input))
}

// SendAgentTextMessage 向已有 AI 会话发送文本消息。
func (s *Service) SendAgentTextMessage(ctx context.Context, meta RequestMeta, conversationID string, input AgentTextMessageInput) (ConversationMessage, error) {
	return WithNormalizedSlices(s.backend.SendAgentTextMessage(ctx, meta, conversationID, input))
}

// StopAgentReply 停止独立 AI 会话中指定的回复并返回实际运行状态。
func (s *Service) StopAgentReply(ctx context.Context, meta RequestMeta, conversationID string, runID string) (AgentRunStatus, error) {
	return WithNormalizedSlices(s.backend.StopAgentReply(ctx, meta, conversationID, runID))
}

// FindDirectConversation 按目标身份查找当前成员的活跃单聊。
func (s *Service) FindDirectConversation(ctx context.Context, meta RequestMeta, targetIdentityID string) (DirectConversationLookup, error) {
	return WithNormalizedSlices(s.backend.FindDirectConversation(ctx, meta, targetIdentityID))
}

// SendDirectTextMessage 发送内部单聊文本消息。
func (s *Service) SendDirectTextMessage(ctx context.Context, meta RequestMeta, conversationID string, input DirectTextMessageInput) (ConversationMessage, error) {
	return WithNormalizedSlices(s.backend.SendDirectTextMessage(ctx, meta, conversationID, input))
}

// CreateGroupConversation 创建企业内部群聊。
func (s *Service) CreateGroupConversation(ctx context.Context, meta RequestMeta, input GroupConversationInput) (InboxConversation, error) {
	return WithNormalizedSlices(s.backend.CreateGroupConversation(ctx, meta, input))
}

// GetGroupConversation 返回当前成员可见的群聊资料。
func (s *Service) GetGroupConversation(ctx context.Context, meta RequestMeta, conversationID string) (GroupConversation, error) {
	return WithNormalizedSlices(s.backend.GetGroupConversation(ctx, meta, conversationID))
}

// UpdateGroupConversation 修改群聊资料。
func (s *Service) UpdateGroupConversation(ctx context.Context, meta RequestMeta, conversationID string, input GroupConversationProfileInput) (GroupConversation, error) {
	return WithNormalizedSlices(s.backend.UpdateGroupConversation(ctx, meta, conversationID, input))
}

// AddGroupConversationMembers 批量增加群聊成员。
func (s *Service) AddGroupConversationMembers(ctx context.Context, meta RequestMeta, conversationID string, input GroupConversationMembersInput) (GroupConversation, error) {
	return WithNormalizedSlices(s.backend.AddGroupConversationMembers(ctx, meta, conversationID, input))
}

// RemoveGroupConversationMember 移除单个群聊成员。
func (s *Service) RemoveGroupConversationMember(ctx context.Context, meta RequestMeta, conversationID string, input GroupConversationMemberInput) (GroupConversation, error) {
	return WithNormalizedSlices(s.backend.RemoveGroupConversationMember(ctx, meta, conversationID, input))
}

// TransferGroupConversationOwner 转让群主。
func (s *Service) TransferGroupConversationOwner(ctx context.Context, meta RequestMeta, conversationID string, input GroupConversationOwnerInput) (GroupConversation, error) {
	return WithNormalizedSlices(s.backend.TransferGroupConversationOwner(ctx, meta, conversationID, input))
}

// LeaveGroupConversation 退出普通成员参与的群聊。
func (s *Service) LeaveGroupConversation(ctx context.Context, meta RequestMeta, conversationID string) error {
	return s.backend.LeaveGroupConversation(ctx, meta, conversationID)
}

// DissolveGroupConversation 解散群聊并保留当前成员的只读历史。
func (s *Service) DissolveGroupConversation(ctx context.Context, meta RequestMeta, conversationID string) (GroupConversation, error) {
	return WithNormalizedSlices(s.backend.DissolveGroupConversation(ctx, meta, conversationID))
}

// SendGroupTextMessage 发送企业内部群聊文本消息。
func (s *Service) SendGroupTextMessage(ctx context.Context, meta RequestMeta, conversationID string, input GroupTextMessageInput) (ConversationMessage, error) {
	return WithNormalizedSlices(s.backend.SendGroupTextMessage(ctx, meta, conversationID, input))
}

// StopGroupAgentReply 停止群聊中指定的 AI 员工回复并返回实际运行状态。
func (s *Service) StopGroupAgentReply(ctx context.Context, meta RequestMeta, conversationID string, runID string) (AgentRunStatus, error) {
	return WithNormalizedSlices(s.backend.StopGroupAgentReply(ctx, meta, conversationID, runID))
}

// GetAgentRunProcess 返回一次已完成运行的有序过程内容和模型用量。
func (s *Service) GetAgentRunProcess(ctx context.Context, meta RequestMeta, runID string) (AgentRunProcess, error) {
	return WithNormalizedSlices(s.backend.GetAgentRunProcess(ctx, meta, runID))
}

// AuthorizeAgentRunStreamAccess 校验当前成员对运行所属会话的阅读资格，原生端读取本机执行中运行的过程流前调用。
func (s *Service) AuthorizeAgentRunStreamAccess(ctx context.Context, meta RequestMeta, runID string) error {
	return s.backend.AuthorizeAgentRunStreamAccess(ctx, meta, runID)
}

// ListMessageChannels 返回消息渠道列表。
func (s *Service) ListMessageChannels(ctx context.Context, meta RequestMeta) (MessageChannelList, error) {
	return WithNormalizedSlices(s.backend.ListMessageChannels(ctx, meta))
}

// GetWebsiteChannel 返回网站渠道详情。
func (s *Service) GetWebsiteChannel(ctx context.Context, meta RequestMeta, channelID string) (WebsiteChannel, error) {
	return WithNormalizedSlices(s.backend.GetWebsiteChannel(ctx, meta, channelID))
}

// GetTelegramChannel 返回 Telegram 渠道详情。
func (s *Service) GetTelegramChannel(ctx context.Context, meta RequestMeta, channelID string) (TelegramChannel, error) {
	return WithNormalizedSlices(s.backend.GetTelegramChannel(ctx, meta, channelID))
}

// TestTelegramChannelConnection 测试 Telegram 草稿 Token。
func (s *Service) TestTelegramChannelConnection(ctx context.Context, meta RequestMeta, channelID string, input TelegramChannelConnectionTestInput) error {
	return s.backend.TestTelegramChannelConnection(ctx, meta, channelID, input)
}

// SaveTelegramChannelConnection 保存 Telegram 机器人和 Webhook 设置。
func (s *Service) SaveTelegramChannelConnection(ctx context.Context, meta RequestMeta, channelID string, input TelegramChannelConnectionInput) (TelegramChannel, error) {
	return WithNormalizedSlices(s.backend.SaveTelegramChannelConnection(ctx, meta, channelID, input))
}

// GetMessageChannel 返回消息渠道基础信息。
func (s *Service) GetMessageChannel(ctx context.Context, meta RequestMeta, channelID string) (MessageChannelSummary, error) {
	return WithNormalizedSlices(s.backend.GetMessageChannel(ctx, meta, channelID))
}

// CreateMessageChannel 创建消息渠道。
func (s *Service) CreateMessageChannel(ctx context.Context, meta RequestMeta, input CreateMessageChannelInput) (MessageChannelSummary, error) {
	return WithNormalizedSlices(s.backend.CreateMessageChannel(ctx, meta, input))
}

// UpdateMessageChannel 修改消息渠道基础信息。
func (s *Service) UpdateMessageChannel(ctx context.Context, meta RequestMeta, channelID string, input MessageChannelBasicsInput) (MessageChannelSummary, error) {
	return WithNormalizedSlices(s.backend.UpdateMessageChannel(ctx, meta, channelID, input))
}

// UpdateMessageChannelReception 修改消息渠道接待设置。
func (s *Service) UpdateMessageChannelReception(ctx context.Context, meta RequestMeta, channelID string, input MessageChannelReceptionInput) (MessageChannelSummary, error) {
	return WithNormalizedSlices(s.backend.UpdateMessageChannelReception(ctx, meta, channelID, input))
}

// UpdateWebsiteChannelChatInterface 修改网站渠道聊天窗口外观与对话功能。
func (s *Service) UpdateWebsiteChannelChatInterface(ctx context.Context, meta RequestMeta, channelID string, input WebsiteChannelChatInterfaceInput) (WebsiteChannelChatInterface, error) {
	return WithNormalizedSlices(s.backend.UpdateWebsiteChannelChatInterface(ctx, meta, channelID, input))
}

// UpdateWebsiteChannelAccess 修改网站渠道允许使用的网站。
func (s *Service) UpdateWebsiteChannelAccess(ctx context.Context, meta RequestMeta, channelID string, input WebsiteChannelAccessInput) (WebsiteChannelAccess, error) {
	return WithNormalizedSlices(s.backend.UpdateWebsiteChannelAccess(ctx, meta, channelID, input))
}

// UpdateWebsiteChannelHome 修改网站渠道 Messenger 首页。
func (s *Service) UpdateWebsiteChannelHome(ctx context.Context, meta RequestMeta, channelID string, input WebsiteChannelHomeInput) (WebsiteChannelHome, error) {
	return WithNormalizedSlices(s.backend.UpdateWebsiteChannelHome(ctx, meta, channelID, input))
}

// UpdateWebsiteChannelHelpCenter 修改网站渠道帮助页签开关与发布的知识库。
func (s *Service) UpdateWebsiteChannelHelpCenter(ctx context.Context, meta RequestMeta, channelID string, input WebsiteChannelHelpCenterInput) (WebsiteChannelHelpCenter, error) {
	return WithNormalizedSlices(s.backend.UpdateWebsiteChannelHelpCenter(ctx, meta, channelID, input))
}

// DeactivateMessageChannel 停用消息渠道。
func (s *Service) DeactivateMessageChannel(ctx context.Context, meta RequestMeta, channelID string) (MessageChannelSummary, error) {
	return WithNormalizedSlices(s.backend.DeactivateMessageChannel(ctx, meta, channelID))
}

// ActivateMessageChannel 启用消息渠道。
func (s *Service) ActivateMessageChannel(ctx context.Context, meta RequestMeta, channelID string) (MessageChannelSummary, error) {
	return WithNormalizedSlices(s.backend.ActivateMessageChannel(ctx, meta, channelID))
}

// ListChannelOptions 返回当前企业的渠道选择项。
func (s *Service) ListChannelOptions(ctx context.Context, meta RequestMeta) (ChannelOptionList, error) {
	return WithNormalizedSlices(s.backend.ListChannelOptions(ctx, meta))
}

// ListMemberOptions 返回可分配的企业成员和 AI 员工。
func (s *Service) ListMemberOptions(ctx context.Context, meta RequestMeta, input MemberOptionListInput) (MemberOptionList, error) {
	return WithNormalizedSlices(s.backend.ListMemberOptions(ctx, meta, input))
}

// ListColleagues 返回通讯录同事目录，服务台排在成员之前。
func (s *Service) ListColleagues(ctx context.Context, meta RequestMeta, input ColleagueListInput) (ColleagueList, error) {
	return WithNormalizedSlices(s.backend.ListColleagues(ctx, meta, input))
}

// ListAgentMCPServerOptions 返回当前企业可配置的 MCP 服务。
func (s *Service) ListAgentMCPServerOptions(ctx context.Context, meta RequestMeta) (AgentMCPServerOptionList, error) {
	return WithNormalizedSlices(s.backend.ListAgentMCPServerOptions(ctx, meta))
}

// ListAgentModelOptions 返回 AI 员工可使用的对话模型。
func (s *Service) ListAgentModelOptions(ctx context.Context, meta RequestMeta) (AgentModelOptionList, error) {
	return WithNormalizedSlices(s.backend.ListAgentModelOptions(ctx, meta))
}

// CreateAgent 创建企业 AI 员工。
func (s *Service) CreateAgent(ctx context.Context, meta RequestMeta, input CreateAgentInput) (Agent, error) {
	return WithNormalizedSlices(s.backend.CreateAgent(ctx, meta, input))
}

// ListAgents 返回企业 AI 员工目录。
func (s *Service) ListAgents(ctx context.Context, meta RequestMeta, input AgentListInput) (AgentList, error) {
	return WithNormalizedSlices(s.backend.ListAgents(ctx, meta, input))
}

// GetAgent 返回企业 AI 员工详情。
func (s *Service) GetAgent(ctx context.Context, meta RequestMeta, agentID string) (Agent, error) {
	return WithNormalizedSlices(s.backend.GetAgent(ctx, meta, agentID))
}

// UpdateAgent 修改企业 AI 员工。
func (s *Service) UpdateAgent(ctx context.Context, meta RequestMeta, agentID string, input UpdateAgentInput) (Agent, error) {
	return WithNormalizedSlices(s.backend.UpdateAgent(ctx, meta, agentID, input))
}

// UpdateAgentExecution 修改企业 AI 员工的执行配置。
func (s *Service) UpdateAgentExecution(ctx context.Context, meta RequestMeta, agentID string, input UpdateAgentExecutionInput) (Agent, error) {
	return WithNormalizedSlices(s.backend.UpdateAgentExecution(ctx, meta, agentID, input))
}

// DeactivateAgent 禁用企业 AI 员工账号。
func (s *Service) DeactivateAgent(ctx context.Context, meta RequestMeta, agentID string) (Agent, error) {
	return WithNormalizedSlices(s.backend.DeactivateAgent(ctx, meta, agentID))
}

// ReactivateAgent 恢复企业 AI 员工。
func (s *Service) ReactivateAgent(ctx context.Context, meta RequestMeta, agentID string) (Agent, error) {
	return WithNormalizedSlices(s.backend.ReactivateAgent(ctx, meta, agentID))
}

// GetAgentEvaluation 返回 AI 员工评测页的最近两次运行与全部用例。
func (s *Service) GetAgentEvaluation(ctx context.Context, meta RequestMeta, agentID string) (AgentEvaluation, error) {
	return WithNormalizedSlices(s.backend.GetAgentEvaluation(ctx, meta, agentID))
}

// StartAgentEvaluationRun 用 AI 员工当前生效的配置对全部用例发起一次评测运行。
func (s *Service) StartAgentEvaluationRun(ctx context.Context, meta RequestMeta, agentID string) error {
	return s.backend.StartAgentEvaluationRun(ctx, meta, agentID)
}

// CreateAgentEvaluationCase 为 AI 员工新建手动评测用例。
func (s *Service) CreateAgentEvaluationCase(ctx context.Context, meta RequestMeta, agentID string, input AgentEvaluationCaseInput) (AgentEvaluationCase, error) {
	return WithNormalizedSlices(s.backend.CreateAgentEvaluationCase(ctx, meta, agentID, input))
}

// GetAgentEvaluationCase 返回评测用例与它在最近一次运行中的全部尝试。
func (s *Service) GetAgentEvaluationCase(ctx context.Context, meta RequestMeta, agentID string, caseID string) (AgentEvaluationCaseDetail, error) {
	return WithNormalizedSlices(s.backend.GetAgentEvaluationCase(ctx, meta, agentID, caseID))
}

// UpdateAgentEvaluationCase 修改评测用例。
func (s *Service) UpdateAgentEvaluationCase(ctx context.Context, meta RequestMeta, agentID string, caseID string, input AgentEvaluationCaseInput) (AgentEvaluationCase, error) {
	return WithNormalizedSlices(s.backend.UpdateAgentEvaluationCase(ctx, meta, agentID, caseID, input))
}

// DeleteAgentEvaluationCase 删除评测用例。
func (s *Service) DeleteAgentEvaluationCase(ctx context.Context, meta RequestMeta, agentID string, caseID string) error {
	return s.backend.DeleteAgentEvaluationCase(ctx, meta, agentID, caseID)
}

// RerunAgentEvaluationCase 在最近一次运行中重新运行一条用例。
func (s *Service) RerunAgentEvaluationCase(ctx context.Context, meta RequestMeta, agentID string, caseID string) error {
	return s.backend.RerunAgentEvaluationCase(ctx, meta, agentID, caseID)
}

// ListPersonalAgents 返回当前成员负责的个人 AI 员工。
func (s *Service) ListPersonalAgents(ctx context.Context, meta RequestMeta) (PersonalAgentList, error) {
	return WithNormalizedSlices(s.backend.ListPersonalAgents(ctx, meta))
}

// ListMemberPersonalAgents 返回指定成员负责的个人 AI 员工。
func (s *Service) ListMemberPersonalAgents(ctx context.Context, meta RequestMeta, userID string) (PersonalAgentList, error) {
	return WithNormalizedSlices(s.backend.ListMemberPersonalAgents(ctx, meta, userID))
}

// GetPersonalAgent 返回当前成员负责的个人 AI 员工详情。
func (s *Service) GetPersonalAgent(ctx context.Context, meta RequestMeta, agentID string) (PersonalAgentDetail, error) {
	return WithNormalizedSlices(s.backend.GetPersonalAgent(ctx, meta, agentID))
}

// CreatePersonalAgent 在当前成员的电脑上创建个人 AI 员工。
func (s *Service) CreatePersonalAgent(ctx context.Context, meta RequestMeta, input CreatePersonalAgentInput) (PersonalAgent, error) {
	return WithNormalizedSlices(s.backend.CreatePersonalAgent(ctx, meta, input))
}

// UpdatePersonalAgent 修改当前成员负责的个人 AI 员工。
func (s *Service) UpdatePersonalAgent(ctx context.Context, meta RequestMeta, agentID string, input PersonalAgentInput) (PersonalAgent, error) {
	return WithNormalizedSlices(s.backend.UpdatePersonalAgent(ctx, meta, agentID, input))
}

// PausePersonalAgent 暂停当前成员负责的个人 AI 员工。
func (s *Service) PausePersonalAgent(ctx context.Context, meta RequestMeta, agentID string) (PersonalAgent, error) {
	return WithNormalizedSlices(s.backend.PausePersonalAgent(ctx, meta, agentID))
}

// ResumePersonalAgent 恢复当前成员负责的已暂停个人 AI 员工。
func (s *Service) ResumePersonalAgent(ctx context.Context, meta RequestMeta, agentID string) (PersonalAgent, error) {
	return WithNormalizedSlices(s.backend.ResumePersonalAgent(ctx, meta, agentID))
}

// MovePersonalAgent 把当前成员负责的个人 AI 员工换到指定电脑。
func (s *Service) MovePersonalAgent(ctx context.Context, meta RequestMeta, agentID string, input PersonalAgentDeviceInput) (PersonalAgent, error) {
	return WithNormalizedSlices(s.backend.MovePersonalAgent(ctx, meta, agentID, input))
}

// DeactivatePersonalAgent 停用个人 AI 员工。
func (s *Service) DeactivatePersonalAgent(ctx context.Context, meta RequestMeta, agentID string) (PersonalAgent, error) {
	return WithNormalizedSlices(s.backend.DeactivatePersonalAgent(ctx, meta, agentID))
}

// ReactivatePersonalAgent 启用已停用的个人 AI 员工。
func (s *Service) ReactivatePersonalAgent(ctx context.Context, meta RequestMeta, agentID string) (PersonalAgent, error) {
	return WithNormalizedSlices(s.backend.ReactivatePersonalAgent(ctx, meta, agentID))
}

// ListAgentMemories 返回当前成员负责的个人 AI 员工的记忆，按最近更新排列。
func (s *Service) ListAgentMemories(ctx context.Context, meta RequestMeta, agentID string) (AgentMemoryList, error) {
	return WithNormalizedSlices(s.backend.ListAgentMemories(ctx, meta, agentID))
}

// UpdateAgentMemory 修改当前成员负责的个人 AI 员工的一条记忆。
func (s *Service) UpdateAgentMemory(ctx context.Context, meta RequestMeta, agentID string, memoryID string, input AgentMemoryInput) (AgentMemory, error) {
	return WithNormalizedSlices(s.backend.UpdateAgentMemory(ctx, meta, agentID, memoryID, input))
}

// DeleteAgentMemory 删除当前成员负责的个人 AI 员工的一条记忆。
func (s *Service) DeleteAgentMemory(ctx context.Context, meta RequestMeta, agentID string, memoryID string) error {
	return s.backend.DeleteAgentMemory(ctx, meta, agentID, memoryID)
}

// ListUsers 返回企业成员列表。
func (s *Service) ListUsers(ctx context.Context, meta RequestMeta, input UserListInput) (UserList, error) {
	return WithNormalizedSlices(s.backend.ListUsers(ctx, meta, input))
}

// GetUser 返回企业成员详情。
func (s *Service) GetUser(ctx context.Context, meta RequestMeta, userID string) (User, error) {
	return WithNormalizedSlices(s.backend.GetUser(ctx, meta, userID))
}

// ListInvitations 返回当前工作区待接受的成员邀请。
func (s *Service) ListInvitations(ctx context.Context, meta RequestMeta) (InvitationList, error) {
	return WithNormalizedSlices(s.backend.ListInvitations(ctx, meta))
}

// CreateInvitation 邀请账号加入当前工作区，返回只展示一次的邀请链接。
func (s *Service) CreateInvitation(ctx context.Context, meta RequestMeta, input InvitationInput) (InvitationCreated, error) {
	return WithNormalizedSlices(s.backend.CreateInvitation(ctx, meta, input))
}

// RegenerateInvitation 撤销原邀请并以相同内容重新生成邀请链接。
func (s *Service) RegenerateInvitation(ctx context.Context, meta RequestMeta, invitationID string) (InvitationCreated, error) {
	return WithNormalizedSlices(s.backend.RegenerateInvitation(ctx, meta, invitationID))
}

// RevokeInvitation 撤销待接受的邀请。
func (s *Service) RevokeInvitation(ctx context.Context, meta RequestMeta, invitationID string) error {
	return s.backend.RevokeInvitation(ctx, meta, invitationID)
}

// PreviewInvitation 按邀请令牌返回工作区名称、邀请人和掩码后的受邀邮箱。
func (s *Service) PreviewInvitation(ctx context.Context, meta RequestMeta, input InvitationTokenInput) (InvitationPreview, error) {
	return WithNormalizedSlices(s.backend.PreviewInvitation(ctx, meta, input))
}

// AcceptInvitation 由当前账号接受邀请并加入工作区。
func (s *Service) AcceptInvitation(ctx context.Context, meta RequestMeta, input InvitationTokenInput) (Workspace, error) {
	return WithNormalizedSlices(s.backend.AcceptInvitation(ctx, meta, input))
}

// GetDeploymentOverview 返回实例标识、服务端版本、账号与工作区数量和实例能力。
func (s *Service) GetDeploymentOverview(ctx context.Context, meta RequestMeta) (DeploymentOverview, error) {
	return WithNormalizedSlices(s.backend.GetDeploymentOverview(ctx, meta))
}

// GetDeploymentSettings 返回部署注册策略和工作区创建策略。
func (s *Service) GetDeploymentSettings(ctx context.Context, meta RequestMeta) (DeploymentSettings, error) {
	return WithNormalizedSlices(s.backend.GetDeploymentSettings(ctx, meta))
}

// UpdateDeploymentSettings 修改部署注册策略和工作区创建策略。
func (s *Service) UpdateDeploymentSettings(ctx context.Context, meta RequestMeta, input DeploymentSettings) (DeploymentSettings, error) {
	return WithNormalizedSlices(s.backend.UpdateDeploymentSettings(ctx, meta, input))
}

// ListDeploymentAccounts 返回部署内的账号。
func (s *Service) ListDeploymentAccounts(ctx context.Context, meta RequestMeta, input DeploymentAccountListInput) (DeploymentAccountList, error) {
	return WithNormalizedSlices(s.backend.ListDeploymentAccounts(ctx, meta, input))
}

// DeactivateDeploymentAccount 停用其他账号并使其登录会话失效。
func (s *Service) DeactivateDeploymentAccount(ctx context.Context, meta RequestMeta, accountID string) (DeploymentAccount, error) {
	return WithNormalizedSlices(s.backend.DeactivateDeploymentAccount(ctx, meta, accountID))
}

// ReactivateDeploymentAccount 恢复已停用的其他账号。
func (s *Service) ReactivateDeploymentAccount(ctx context.Context, meta RequestMeta, accountID string) (DeploymentAccount, error) {
	return WithNormalizedSlices(s.backend.ReactivateDeploymentAccount(ctx, meta, accountID))
}

// GrantDeploymentAdmin 把其他账号设为部署管理员。
func (s *Service) GrantDeploymentAdmin(ctx context.Context, meta RequestMeta, accountID string) (DeploymentAccount, error) {
	return WithNormalizedSlices(s.backend.GrantDeploymentAdmin(ctx, meta, accountID))
}

// RevokeDeploymentAdmin 撤销其他账号的部署管理员身份。
func (s *Service) RevokeDeploymentAdmin(ctx context.Context, meta RequestMeta, accountID string) (DeploymentAccount, error) {
	return WithNormalizedSlices(s.backend.RevokeDeploymentAdmin(ctx, meta, accountID))
}

// ListDeploymentWorkspaces 返回部署内的全部工作区。
func (s *Service) ListDeploymentWorkspaces(ctx context.Context, meta RequestMeta, input DeploymentWorkspaceListInput) (DeploymentWorkspaceList, error) {
	return WithNormalizedSlices(s.backend.ListDeploymentWorkspaces(ctx, meta, input))
}

// UpdateUser 修改企业成员头像、资料、角色和所属团队。
func (s *Service) UpdateUser(ctx context.Context, meta RequestMeta, userID string, input UpdateUserInput) (User, error) {
	return WithNormalizedSlices(s.backend.UpdateUser(ctx, meta, userID, input))
}

// UpdateRoleAssignments 在一个事务中批量调整成员角色。
func (s *Service) UpdateRoleAssignments(ctx context.Context, meta RequestMeta, input RoleAssignmentsInput) error {
	return s.backend.UpdateRoleAssignments(ctx, meta, input)
}

// DeactivateUser 禁用企业成员账号。
func (s *Service) DeactivateUser(ctx context.Context, meta RequestMeta, userID string) (User, error) {
	return WithNormalizedSlices(s.backend.DeactivateUser(ctx, meta, userID))
}

// ReactivateUser 恢复企业成员账号。
func (s *Service) ReactivateUser(ctx context.Context, meta RequestMeta, userID string) (User, error) {
	return WithNormalizedSlices(s.backend.ReactivateUser(ctx, meta, userID))
}

// ListTeams 返回企业团队列表。
func (s *Service) ListTeams(ctx context.Context, meta RequestMeta, input TeamListInput) (TeamList, error) {
	return WithNormalizedSlices(s.backend.ListTeams(ctx, meta, input))
}

// GetTeam 返回团队详情。
func (s *Service) GetTeam(ctx context.Context, meta RequestMeta, teamID string) (Team, error) {
	return WithNormalizedSlices(s.backend.GetTeam(ctx, meta, teamID))
}

// CreateTeam 创建企业团队。
func (s *Service) CreateTeam(ctx context.Context, meta RequestMeta, input TeamInput) (Team, error) {
	return WithNormalizedSlices(s.backend.CreateTeam(ctx, meta, input))
}

// UpdateTeam 修改企业团队。
func (s *Service) UpdateTeam(ctx context.Context, meta RequestMeta, teamID string, input TeamInput) (Team, error) {
	return WithNormalizedSlices(s.backend.UpdateTeam(ctx, meta, teamID, input))
}

// DeleteTeam 删除企业团队及其成员关系。
func (s *Service) DeleteTeam(ctx context.Context, meta RequestMeta, teamID string) error {
	return s.backend.DeleteTeam(ctx, meta, teamID)
}

// ListTeamMembers 返回团队成员列表。
func (s *Service) ListTeamMembers(ctx context.Context, meta RequestMeta, teamID string, input TeamMemberListInput) (TeamMemberList, error) {
	return WithNormalizedSlices(s.backend.ListTeamMembers(ctx, meta, teamID, input))
}

// ListTeamMemberCandidates 返回尚未加入团队的企业身份。
func (s *Service) ListTeamMemberCandidates(ctx context.Context, meta RequestMeta, teamID string, input TeamMemberCandidateInput) (TeamMemberCandidateList, error) {
	return WithNormalizedSlices(s.backend.ListTeamMemberCandidates(ctx, meta, teamID, input))
}

// AddTeamMembers 将企业身份批量加入团队。
func (s *Service) AddTeamMembers(ctx context.Context, meta RequestMeta, teamID string, input TeamMemberInput) (Team, error) {
	return WithNormalizedSlices(s.backend.AddTeamMembers(ctx, meta, teamID, input))
}

// RemoveTeamMembers 将企业身份批量移出团队。
func (s *Service) RemoveTeamMembers(ctx context.Context, meta RequestMeta, teamID string, input TeamMemberInput) (Team, error) {
	return WithNormalizedSlices(s.backend.RemoveTeamMembers(ctx, meta, teamID, input))
}

// RetryKnowledgeDocument 按当前配置重新处理文档。
func (s *Service) RetryKnowledgeDocument(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string) error {
	return s.backend.RetryKnowledgeDocument(ctx, meta, knowledgeBaseID, documentID)
}

// ListKnowledgeDocumentSegments 返回固定批次的分段页或锚点所在页。
func (s *Service) ListKnowledgeDocumentSegments(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string, input KnowledgeDocumentSegmentInput) (KnowledgeDocumentSegmentPage, error) {
	return WithNormalizedSlices(s.backend.ListKnowledgeDocumentSegments(ctx, meta, knowledgeBaseID, documentID, input))
}

// RetrieveKnowledgeBase 在指定知识库中执行检索测试，返回混合召回与重排后的分段。
func (s *Service) RetrieveKnowledgeBase(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeRetrievalInput) (KnowledgeRetrievalResult, error) {
	return WithNormalizedSlices(s.backend.RetrieveKnowledgeBase(ctx, meta, knowledgeBaseID, input))
}

// ListKnowledgeDocuments 返回当前分组的文档列表。
func (s *Service) ListKnowledgeDocuments(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeDocumentListInput) (KnowledgeDocumentList, error) {
	return WithNormalizedSlices(s.backend.ListKnowledgeDocuments(ctx, meta, knowledgeBaseID, input))
}

// GetKnowledgeDocument 返回文档详情。
func (s *Service) GetKnowledgeDocument(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string) (KnowledgeDocument, error) {
	return WithNormalizedSlices(s.backend.GetKnowledgeDocument(ctx, meta, knowledgeBaseID, documentID))
}

// CreateKnowledgeDocuments 保存最多十个已上传的文档原件。
func (s *Service) CreateKnowledgeDocuments(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeDocumentBatchInput) (KnowledgeDocumentBatch, error) {
	return WithNormalizedSlices(s.backend.CreateKnowledgeDocuments(ctx, meta, knowledgeBaseID, input))
}

// DeleteKnowledgeDocument 删除文档并释放原件。
func (s *Service) DeleteKnowledgeDocument(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string) error {
	return s.backend.DeleteKnowledgeDocument(ctx, meta, knowledgeBaseID, documentID)
}

// GetKnowledgeDocumentPreview 签发当前文档的原件预览请求。
func (s *Service) GetKnowledgeDocumentPreview(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string) (KnowledgeDocumentPreviewRequest, error) {
	return WithNormalizedSlices(s.backend.GetKnowledgeDocumentPreview(ctx, meta, knowledgeBaseID, documentID))
}

// CreateKnowledgeTextDocument 创建在线编写的文档并安排索引。
func (s *Service) CreateKnowledgeTextDocument(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeTextDocumentInput) (KnowledgeDocument, error) {
	return WithNormalizedSlices(s.backend.CreateKnowledgeTextDocument(ctx, meta, knowledgeBaseID, input))
}

// GetKnowledgeDocumentContent 返回在线文档正文或网页抓取快照。
func (s *Service) GetKnowledgeDocumentContent(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string) (KnowledgeDocumentContent, error) {
	return WithNormalizedSlices(s.backend.GetKnowledgeDocumentContent(ctx, meta, knowledgeBaseID, documentID))
}

// UpdateKnowledgeDocumentContent 修改在线文档的名称与正文并安排索引。
func (s *Service) UpdateKnowledgeDocumentContent(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string, input KnowledgeDocumentContentInput) (KnowledgeDocument, error) {
	return WithNormalizedSlices(s.backend.UpdateKnowledgeDocumentContent(ctx, meta, knowledgeBaseID, documentID, input))
}

// RenameKnowledgeDocument 修改在线文档或网页文档的名称。
func (s *Service) RenameKnowledgeDocument(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string, input KnowledgeDocumentRenameInput) (KnowledgeDocument, error) {
	return WithNormalizedSlices(s.backend.RenameKnowledgeDocument(ctx, meta, knowledgeBaseID, documentID, input))
}

// CreateKnowledgeWebDocument 导入网页并安排首次抓取。
func (s *Service) CreateKnowledgeWebDocument(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeWebDocumentInput) (KnowledgeDocument, error) {
	return WithNormalizedSlices(s.backend.CreateKnowledgeWebDocument(ctx, meta, knowledgeBaseID, input))
}

// RefetchKnowledgeDocument 重新抓取网页文档并重新索引。
func (s *Service) RefetchKnowledgeDocument(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string, input KnowledgeDocumentRefetchInput) error {
	return s.backend.RefetchKnowledgeDocument(ctx, meta, knowledgeBaseID, documentID, input)
}

// ListKnowledgeQAEntries 返回分组中的本地问答列表。
func (s *Service) ListKnowledgeQAEntries(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeQAListInput) (KnowledgeQAList, error) {
	return WithNormalizedSlices(s.backend.ListKnowledgeQAEntries(ctx, meta, knowledgeBaseID, input))
}

// GetKnowledgeQAEntry 返回完整的本地问答。
func (s *Service) GetKnowledgeQAEntry(ctx context.Context, meta RequestMeta, knowledgeBaseID string, entryID string) (KnowledgeQAEntry, error) {
	return WithNormalizedSlices(s.backend.GetKnowledgeQAEntry(ctx, meta, knowledgeBaseID, entryID))
}

// CreateKnowledgeQAEntry 创建本地问答。
func (s *Service) CreateKnowledgeQAEntry(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeQAInput) (KnowledgeQAEntry, error) {
	return WithNormalizedSlices(s.backend.CreateKnowledgeQAEntry(ctx, meta, knowledgeBaseID, input))
}

// UpdateKnowledgeQAEntry 修改本地问答。
func (s *Service) UpdateKnowledgeQAEntry(ctx context.Context, meta RequestMeta, knowledgeBaseID string, entryID string, input KnowledgeQAInput) (KnowledgeQAEntry, error) {
	return WithNormalizedSlices(s.backend.UpdateKnowledgeQAEntry(ctx, meta, knowledgeBaseID, entryID, input))
}

// DeleteKnowledgeQAEntry 删除本地问答。
func (s *Service) DeleteKnowledgeQAEntry(ctx context.Context, meta RequestMeta, knowledgeBaseID string, entryID string) error {
	return s.backend.DeleteKnowledgeQAEntry(ctx, meta, knowledgeBaseID, entryID)
}

// RetryKnowledgeQAEntry 按当前配置重新索引问答。
func (s *Service) RetryKnowledgeQAEntry(ctx context.Context, meta RequestMeta, knowledgeBaseID string, entryID string) error {
	return s.backend.RetryKnowledgeQAEntry(ctx, meta, knowledgeBaseID, entryID)
}

// ListKnowledgeBases 返回当前企业的知识库列表。
func (s *Service) ListKnowledgeBases(ctx context.Context, meta RequestMeta) (KnowledgeBaseList, error) {
	return WithNormalizedSlices(s.backend.ListKnowledgeBases(ctx, meta))
}

// GetKnowledgeBase 返回当前企业中的知识库详情。
func (s *Service) GetKnowledgeBase(ctx context.Context, meta RequestMeta, knowledgeBaseID string) (KnowledgeBase, error) {
	return WithNormalizedSlices(s.backend.GetKnowledgeBase(ctx, meta, knowledgeBaseID))
}

// ListKnowledgeBaseAgents 返回当前配置版本绑定知识库的 AI 员工。
func (s *Service) ListKnowledgeBaseAgents(ctx context.Context, meta RequestMeta, knowledgeBaseID string) (KnowledgeBaseAgentList, error) {
	return WithNormalizedSlices(s.backend.ListKnowledgeBaseAgents(ctx, meta, knowledgeBaseID))
}

// CreateKnowledgeBase 创建企业知识库。
func (s *Service) CreateKnowledgeBase(ctx context.Context, meta RequestMeta, input KnowledgeBaseInput) (KnowledgeBase, error) {
	return WithNormalizedSlices(s.backend.CreateKnowledgeBase(ctx, meta, input))
}

// UpdateKnowledgeBase 修改企业知识库。
func (s *Service) UpdateKnowledgeBase(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeBaseInput) (KnowledgeBase, error) {
	return WithNormalizedSlices(s.backend.UpdateKnowledgeBase(ctx, meta, knowledgeBaseID, input))
}

// DeleteKnowledgeBase 删除企业知识库。
func (s *Service) DeleteKnowledgeBase(ctx context.Context, meta RequestMeta, knowledgeBaseID string) error {
	return s.backend.DeleteKnowledgeBase(ctx, meta, knowledgeBaseID)
}

// ListContacts 返回联系人列表。
func (s *Service) ListContacts(ctx context.Context, meta RequestMeta, input ContactListInput) (ContactList, error) {
	return WithNormalizedSlices(s.backend.ListContacts(ctx, meta, input))
}

// GetContact 返回联系人详情。
func (s *Service) GetContact(ctx context.Context, meta RequestMeta, contactID string) (Contact, error) {
	return WithNormalizedSlices(s.backend.GetContact(ctx, meta, contactID))
}

// CreateContact 创建联系人。
func (s *Service) CreateContact(ctx context.Context, meta RequestMeta, input ContactInput) (Contact, error) {
	return WithNormalizedSlices(s.backend.CreateContact(ctx, meta, input))
}

// UpdateContact 修改联系人。
func (s *Service) UpdateContact(ctx context.Context, meta RequestMeta, contactID string, input ContactInput) (Contact, error) {
	return WithNormalizedSlices(s.backend.UpdateContact(ctx, meta, contactID, input))
}

// DeleteContact 将联系人移入回收站。
func (s *Service) DeleteContact(ctx context.Context, meta RequestMeta, contactID string) error {
	return s.backend.DeleteContact(ctx, meta, contactID)
}

// RestoreContact 恢复联系人。
func (s *Service) RestoreContact(ctx context.Context, meta RequestMeta, contactID string) (Contact, error) {
	return WithNormalizedSlices(s.backend.RestoreContact(ctx, meta, contactID))
}

// SetContactFieldValue 由客服填写或清空联系人字段。
func (s *Service) SetContactFieldValue(ctx context.Context, meta RequestMeta, contactID string, fieldID string, input ContactFieldValueInput) error {
	return s.backend.SetContactFieldValue(ctx, meta, contactID, fieldID, input)
}

// AddContactTag 由客服给联系人添加标签。
func (s *Service) AddContactTag(ctx context.Context, meta RequestMeta, contactID string, tagID string) error {
	return s.backend.AddContactTag(ctx, meta, contactID, tagID)
}

// RemoveContactTag 由客服移除联系人上的标签。
func (s *Service) RemoveContactTag(ctx context.Context, meta RequestMeta, contactID string, tagID string) error {
	return s.backend.RemoveContactTag(ctx, meta, contactID, tagID)
}

// ListRoles 返回当前企业的角色和预定义权限目录。
func (s *Service) ListRoles(ctx context.Context, meta RequestMeta) (RoleList, error) {
	return WithNormalizedSlices(s.backend.ListRoles(ctx, meta))
}

// GetRole 返回当前企业的角色详情。
func (s *Service) GetRole(ctx context.Context, meta RequestMeta, roleID string) (Role, error) {
	return WithNormalizedSlices(s.backend.GetRole(ctx, meta, roleID))
}

// CreateRole 创建自定义角色。
func (s *Service) CreateRole(ctx context.Context, meta RequestMeta, input RoleInput) (Role, error) {
	return WithNormalizedSlices(s.backend.CreateRole(ctx, meta, input))
}

// UpdateRole 修改角色信息和权限。
func (s *Service) UpdateRole(ctx context.Context, meta RequestMeta, roleID string, input RoleInput) (Role, error) {
	return WithNormalizedSlices(s.backend.UpdateRole(ctx, meta, roleID, input))
}

// DeleteRole 删除自定义角色。
func (s *Service) DeleteRole(ctx context.Context, meta RequestMeta, roleID string) error {
	return s.backend.DeleteRole(ctx, meta, roleID)
}

// ListAIProviders 返回当前企业的模型服务供应商列表。
func (s *Service) ListAIProviders(ctx context.Context, meta RequestMeta) (AIProviderList, error) {
	return WithNormalizedSlices(s.backend.ListAIProviders(ctx, meta))
}

// GetAIProvider 返回当前企业中的模型服务供应商详情。
func (s *Service) GetAIProvider(ctx context.Context, meta RequestMeta, providerID string) (AIProvider, error) {
	return WithNormalizedSlices(s.backend.GetAIProvider(ctx, meta, providerID))
}

// ListAvailableAIModels 返回指定品牌的预设模型目录。
func (s *Service) ListAvailableAIModels(ctx context.Context, meta RequestMeta, brand AIProviderBrand) (AIProviderModelList, error) {
	return WithNormalizedSlices(s.backend.ListAvailableAIModels(ctx, meta, brand))
}

// DiscoverAIProviderModels 读取模型服务实例当前可用的模型目录。
func (s *Service) DiscoverAIProviderModels(ctx context.Context, meta RequestMeta, input AIProviderConnectionInput) (AIProviderModelList, error) {
	return WithNormalizedSlices(s.backend.DiscoverAIProviderModels(ctx, meta, input))
}

// TestAIProviderConnection 测试模型服务供应商草稿配置。
func (s *Service) TestAIProviderConnection(ctx context.Context, meta RequestMeta, input AIProviderConnectionInput) error {
	return s.backend.TestAIProviderConnection(ctx, meta, input)
}

// CreateAIProvider 创建模型服务供应商。
func (s *Service) CreateAIProvider(ctx context.Context, meta RequestMeta, input AIProviderInput) (AIProvider, error) {
	return WithNormalizedSlices(s.backend.CreateAIProvider(ctx, meta, input))
}

// UpdateAIProvider 修改模型服务供应商。
func (s *Service) UpdateAIProvider(ctx context.Context, meta RequestMeta, providerID string, input AIProviderUpdateInput) (AIProvider, error) {
	return WithNormalizedSlices(s.backend.UpdateAIProvider(ctx, meta, providerID, input))
}

// DeleteAIProvider 删除模型服务供应商。
func (s *Service) DeleteAIProvider(ctx context.Context, meta RequestMeta, providerID string) error {
	return s.backend.DeleteAIProvider(ctx, meta, providerID)
}

// GetWebSearchSettings 读取当前企业的联网搜索设置。
func (s *Service) GetWebSearchSettings(ctx context.Context, meta RequestMeta) (WebSearchSettings, error) {
	return WithNormalizedSlices(s.backend.GetWebSearchSettings(ctx, meta))
}

// UpdateWebSearchSettings 修改当前企业的联网搜索设置。
func (s *Service) UpdateWebSearchSettings(ctx context.Context, meta RequestMeta, input WebSearchSettings) (WebSearchSettings, error) {
	return WithNormalizedSlices(s.backend.UpdateWebSearchSettings(ctx, meta, input))
}

// TestWebSearchService 用草稿配置执行一次搜索，验证搜索服务可用。
func (s *Service) TestWebSearchService(ctx context.Context, meta RequestMeta, input WebSearchService) error {
	return s.backend.TestWebSearchService(ctx, meta, input)
}

// ListMCPServers 返回当前企业配置的 MCP 服务。
func (s *Service) ListMCPServers(ctx context.Context, meta RequestMeta) (MCPServerList, error) {
	return WithNormalizedSlices(s.backend.ListMCPServers(ctx, meta))
}

// GetMCPServer 返回当前企业中的 MCP 服务详情。
func (s *Service) GetMCPServer(ctx context.Context, meta RequestMeta, mcpServerID string) (MCPServer, error) {
	return WithNormalizedSlices(s.backend.GetMCPServer(ctx, meta, mcpServerID))
}

// TestMCPServerConnection 测试 MCP 草稿连接配置。
func (s *Service) TestMCPServerConnection(ctx context.Context, meta RequestMeta, input MCPServerConnectionInput) error {
	return s.backend.TestMCPServerConnection(ctx, meta, input)
}

// TestSavedMCPServerConnection 测试已保存的 MCP 服务。
func (s *Service) TestSavedMCPServerConnection(ctx context.Context, meta RequestMeta, mcpServerID string) error {
	return s.backend.TestSavedMCPServerConnection(ctx, meta, mcpServerID)
}

// RefreshMCPServerTools 提交当前企业的 MCP 工具更新任务。
func (s *Service) RefreshMCPServerTools(ctx context.Context, meta RequestMeta) error {
	return s.backend.RefreshMCPServerTools(ctx, meta)
}

// CreateMCPServer 创建 MCP 服务。
func (s *Service) CreateMCPServer(ctx context.Context, meta RequestMeta, input MCPServerInput) (MCPServer, error) {
	return WithNormalizedSlices(s.backend.CreateMCPServer(ctx, meta, input))
}

// UpdateMCPServer 修改 MCP 服务。
func (s *Service) UpdateMCPServer(ctx context.Context, meta RequestMeta, mcpServerID string, input MCPServerInput) (MCPServer, error) {
	return WithNormalizedSlices(s.backend.UpdateMCPServer(ctx, meta, mcpServerID, input))
}

// UpdateMCPToolPurpose 标记 MCP 服务中一个工具的用途。
func (s *Service) UpdateMCPToolPurpose(ctx context.Context, meta RequestMeta, mcpServerID string, input MCPToolPurposeInput) (MCPServer, error) {
	return WithNormalizedSlices(s.backend.UpdateMCPToolPurpose(ctx, meta, mcpServerID, input))
}

// DeleteMCPServer 删除 MCP 服务。
func (s *Service) DeleteMCPServer(ctx context.Context, meta RequestMeta, mcpServerID string) error {
	return s.backend.DeleteMCPServer(ctx, meta, mcpServerID)
}

// UpdateOrganization 修改当前工作区的名称。
func (s *Service) UpdateOrganization(ctx context.Context, meta RequestMeta, input OrganizationInput) (Organization, error) {
	return WithNormalizedSlices(s.backend.UpdateOrganization(ctx, meta, input))
}

// GetCustomerIdentitySecret 读取当前企业的客户身份密钥，未生成时为空。
func (s *Service) GetCustomerIdentitySecret(ctx context.Context, meta RequestMeta) (CustomerIdentitySecret, error) {
	return WithNormalizedSlices(s.backend.GetCustomerIdentitySecret(ctx, meta))
}

// RegenerateCustomerIdentitySecret 生成或重新生成当前企业的客户身份密钥，旧密钥立即失效。
func (s *Service) RegenerateCustomerIdentitySecret(ctx context.Context, meta RequestMeta) (CustomerIdentitySecret, error) {
	return WithNormalizedSlices(s.backend.RegenerateCustomerIdentitySecret(ctx, meta))
}

// GetBusinessHours 读取当前企业的客服工作时间。
func (s *Service) GetBusinessHours(ctx context.Context, meta RequestMeta) (BusinessHours, error) {
	return WithNormalizedSlices(s.backend.GetBusinessHours(ctx, meta))
}

// UpdateBusinessHours 修改当前企业的客服工作时间。
func (s *Service) UpdateBusinessHours(ctx context.Context, meta RequestMeta, input BusinessHours) (BusinessHours, error) {
	return WithNormalizedSlices(s.backend.UpdateBusinessHours(ctx, meta, input))
}

// GetServiceTimeouts 读取当前企业的客服超时时长。
func (s *Service) GetServiceTimeouts(ctx context.Context, meta RequestMeta) (ServiceTimeouts, error) {
	return WithNormalizedSlices(s.backend.GetServiceTimeouts(ctx, meta))
}

// UpdateServiceTimeouts 修改当前企业的客服超时时长。
func (s *Service) UpdateServiceTimeouts(ctx context.Context, meta RequestMeta, input ServiceTimeouts) (ServiceTimeouts, error) {
	return WithNormalizedSlices(s.backend.UpdateServiceTimeouts(ctx, meta, input))
}

// GetServiceSummarySettings 读取当前企业的周期小结设置。
func (s *Service) GetServiceSummarySettings(ctx context.Context, meta RequestMeta) (ServiceSummarySettings, error) {
	return WithNormalizedSlices(s.backend.GetServiceSummarySettings(ctx, meta))
}

// UpdateServiceSummarySettings 修改当前企业的周期小结设置。
func (s *Service) UpdateServiceSummarySettings(ctx context.Context, meta RequestMeta, input ServiceSummarySettings) (ServiceSummarySettings, error) {
	return WithNormalizedSlices(s.backend.UpdateServiceSummarySettings(ctx, meta, input))
}

// GetTranslationSettings 读取当前企业的翻译设置。
func (s *Service) GetTranslationSettings(ctx context.Context, meta RequestMeta) (TranslationSettings, error) {
	return WithNormalizedSlices(s.backend.GetTranslationSettings(ctx, meta))
}

// UpdateTranslationSettings 修改当前企业的翻译设置。
func (s *Service) UpdateTranslationSettings(ctx context.Context, meta RequestMeta, input TranslationSettings) (TranslationSettings, error) {
	return WithNormalizedSlices(s.backend.UpdateTranslationSettings(ctx, meta, input))
}

// ListServiceCategories 返回当前企业的咨询分类目录。
func (s *Service) ListServiceCategories(ctx context.Context, meta RequestMeta) (ServiceCategoryList, error) {
	return WithNormalizedSlices(s.backend.ListServiceCategories(ctx, meta))
}

// CreateServiceCategory 新增咨询分类。
func (s *Service) CreateServiceCategory(ctx context.Context, meta RequestMeta, input ServiceCategoryInput) (ServiceCategory, error) {
	return WithNormalizedSlices(s.backend.CreateServiceCategory(ctx, meta, input))
}

// UpdateServiceCategory 修改咨询分类。
func (s *Service) UpdateServiceCategory(ctx context.Context, meta RequestMeta, categoryID string, input ServiceCategoryInput) (ServiceCategory, error) {
	return WithNormalizedSlices(s.backend.UpdateServiceCategory(ctx, meta, categoryID, input))
}

// DeleteServiceCategory 删除咨询分类，历史记录保留分类名称。
func (s *Service) DeleteServiceCategory(ctx context.Context, meta RequestMeta, categoryID string) error {
	return s.backend.DeleteServiceCategory(ctx, meta, categoryID)
}

// ListContactFields 返回当前企业的联系人字段。
func (s *Service) ListContactFields(ctx context.Context, meta RequestMeta) (ContactFieldList, error) {
	return WithNormalizedSlices(s.backend.ListContactFields(ctx, meta))
}

// CreateContactField 新增联系人字段。
func (s *Service) CreateContactField(ctx context.Context, meta RequestMeta, input ContactFieldInput) (ContactField, error) {
	return WithNormalizedSlices(s.backend.CreateContactField(ctx, meta, input))
}

// UpdateContactField 修改联系人字段，被移除的单选选项对应的取值随之清空。
func (s *Service) UpdateContactField(ctx context.Context, meta RequestMeta, fieldID string, input ContactFieldInput) (ContactField, error) {
	return WithNormalizedSlices(s.backend.UpdateContactField(ctx, meta, fieldID, input))
}

// DeleteContactField 删除联系人字段及其全部取值。
func (s *Service) DeleteContactField(ctx context.Context, meta RequestMeta, fieldID string) error {
	return s.backend.DeleteContactField(ctx, meta, fieldID)
}

// ListContactTags 返回当前企业的联系人标签。
func (s *Service) ListContactTags(ctx context.Context, meta RequestMeta) (ContactTagList, error) {
	return WithNormalizedSlices(s.backend.ListContactTags(ctx, meta))
}

// CreateContactTag 新增联系人标签。
func (s *Service) CreateContactTag(ctx context.Context, meta RequestMeta, input ContactTagInput) (ContactTag, error) {
	return WithNormalizedSlices(s.backend.CreateContactTag(ctx, meta, input))
}

// UpdateContactTag 修改联系人标签。
func (s *Service) UpdateContactTag(ctx context.Context, meta RequestMeta, tagID string, input ContactTagInput) (ContactTag, error) {
	return WithNormalizedSlices(s.backend.UpdateContactTag(ctx, meta, tagID, input))
}

// DeleteContactTag 删除联系人标签并从所有联系人上移除。
func (s *Service) DeleteContactTag(ctx context.Context, meta RequestMeta, tagID string) error {
	return s.backend.DeleteContactTag(ctx, meta, tagID)
}

// GetAIPerformanceReport 返回当前企业指定范围内的 AI 客服表现概览。
func (s *Service) GetAIPerformanceReport(ctx context.Context, meta RequestMeta, input AIPerformanceReportInput) (AIPerformanceReport, error) {
	return WithNormalizedSlices(s.backend.GetAIPerformanceReport(ctx, meta, input))
}

// ListAIPerformanceBreakdowns 返回按渠道或咨询分类拆分的一页 AI 客服表现。
func (s *Service) ListAIPerformanceBreakdowns(ctx context.Context, meta RequestMeta, input AIPerformanceBreakdownInput) (AIPerformanceBreakdownList, error) {
	return WithNormalizedSlices(s.backend.ListAIPerformanceBreakdowns(ctx, meta, input))
}

// ListAIPerformanceIssues 返回一页指定类型的 AI 表现问题会话。
func (s *Service) ListAIPerformanceIssues(ctx context.Context, meta RequestMeta, input AIPerformanceIssueListInput) (ServiceIssueList, error) {
	return WithNormalizedSlices(s.backend.ListAIPerformanceIssues(ctx, meta, input))
}

// GetTeamPerformanceReport 返回当前企业指定范围内的真人客服表现概览。
func (s *Service) GetTeamPerformanceReport(ctx context.Context, meta RequestMeta, input TeamPerformanceReportInput) (TeamPerformanceReport, error) {
	return WithNormalizedSlices(s.backend.GetTeamPerformanceReport(ctx, meta, input))
}

// ListTeamPerformanceMembers 返回按客服拆分的一页真人客服表现。
func (s *Service) ListTeamPerformanceMembers(ctx context.Context, meta RequestMeta, input TeamPerformanceMemberListInput) (TeamPerformanceMemberList, error) {
	return WithNormalizedSlices(s.backend.ListTeamPerformanceMembers(ctx, meta, input))
}

// ListTeamPerformanceBreakdowns 返回按渠道或咨询分类拆分的一页真人客服表现。
func (s *Service) ListTeamPerformanceBreakdowns(ctx context.Context, meta RequestMeta, input TeamPerformanceBreakdownInput) (TeamPerformanceBreakdownList, error) {
	return WithNormalizedSlices(s.backend.ListTeamPerformanceBreakdowns(ctx, meta, input))
}

// ListTeamPerformanceIssues 返回一页指定类型的真人接待问题会话。
func (s *Service) ListTeamPerformanceIssues(ctx context.Context, meta RequestMeta, input TeamPerformanceIssueListInput) (ServiceIssueList, error) {
	return WithNormalizedSlices(s.backend.ListTeamPerformanceIssues(ctx, meta, input))
}

// GetServiceIssue 返回客服周期的质检结论与对客沟通。
func (s *Service) GetServiceIssue(ctx context.Context, meta RequestMeta, serviceSessionID string) (ServiceIssueDetail, error) {
	return WithNormalizedSlices(s.backend.GetServiceIssue(ctx, meta, serviceSessionID))
}

// ListAgentServiceSessions 返回 AI 员工接待的一页服务周期。
func (s *Service) ListAgentServiceSessions(ctx context.Context, meta RequestMeta, agentID string, input AgentServiceSessionListInput) (AgentServiceSessionList, error) {
	return WithNormalizedSlices(s.backend.ListAgentServiceSessions(ctx, meta, agentID, input))
}

// ListKnowledgeGaps 返回一页指定处理状态的待补知识。
func (s *Service) ListKnowledgeGaps(ctx context.Context, meta RequestMeta, input KnowledgeGapListInput) (KnowledgeGapList, error) {
	return WithNormalizedSlices(s.backend.ListKnowledgeGaps(ctx, meta, input))
}

// GetKnowledgeGap 返回待补知识详情。
func (s *Service) GetKnowledgeGap(ctx context.Context, meta RequestMeta, gapID string) (KnowledgeGap, error) {
	return WithNormalizedSlices(s.backend.GetKnowledgeGap(ctx, meta, gapID))
}

// AcceptKnowledgeGap 把待补知识整理的问答加入知识库。
func (s *Service) AcceptKnowledgeGap(ctx context.Context, meta RequestMeta, gapID string, input KnowledgeGapAcceptInput) error {
	return s.backend.AcceptKnowledgeGap(ctx, meta, gapID, input)
}

// AddServiceIssueToEvaluation 把应转人工未转的问题会话以选定的客户消息为提问加入负责 AI 员工的评测。
func (s *Service) AddServiceIssueToEvaluation(ctx context.Context, meta RequestMeta, serviceSessionID string, input ServiceIssueEvaluationInput) (AgentEvaluationCase, error) {
	return WithNormalizedSlices(s.backend.AddServiceIssueToEvaluation(ctx, meta, serviceSessionID, input))
}

// DismissKnowledgeGap 忽略待补知识。
func (s *Service) DismissKnowledgeGap(ctx context.Context, meta RequestMeta, gapID string) error {
	return s.backend.DismissKnowledgeGap(ctx, meta, gapID)
}

// RegisterDevice 注册当前用户的本机设备。
func (s *Service) RegisterDevice(ctx context.Context, meta RequestMeta, input DeviceRegistrationInput) (Device, error) {
	return WithNormalizedSlices(s.backend.RegisterDevice(ctx, meta, input))
}

// ListDevices 返回当前用户已注册的设备。
func (s *Service) ListDevices(ctx context.Context, meta RequestMeta) (DeviceList, error) {
	return WithNormalizedSlices(s.backend.ListDevices(ctx, meta))
}

// RevokeDevice 撤销当前用户的设备。
func (s *Service) RevokeDevice(ctx context.Context, meta RequestMeta, deviceID string) error {
	return s.backend.RevokeDevice(ctx, meta, deviceID)
}
