package main

import (
	"fmt"
	"go/constant"
	"go/types"
	"maps"
	"reflect"
	"regexp"
	"slices"
	"strings"
	"unicode"

	"github.com/runforyou-ai/support/arr"
	"github.com/runforyou-ai/support/set"
	"github.com/runforyou-ai/support/str"
)

// typeScriptRoots 是不出现在契约方法签名、但随 HTTP 响应传输的类型：错误响应体及其会话状态与错误类型。
var typeScriptRoots = []string{"Error"}

// typeScriptNames 把与 TypeScript 全局名称冲突的契约类型改名输出。
var typeScriptNames = map[string]string{"Error": "ApiErrorBody"}

// typeScriptConstants 是前端需要读取的接口版本与请求头常量。
var typeScriptConstants = []string{"APIVersion", "MinServerAPIVersion", "ClientAPIVersionHeader", "WorkspaceHeader"}

// identifierPattern 匹配可直接作为 TypeScript 属性名的标识符。
var identifierPattern = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// typeScriptEmitter 从契约方法签名出发收集并输出 TypeScript 类型。
type typeScriptEmitter struct {
	contract *contract
	// optional 记录作为 GET 查询参数的结构体，其字段在前端均可省略。
	optional map[string]bool
	pending  []*types.TypeName
	seen     set.Set[*types.TypeName]
	// core 记录是否引用了核心契约的类型，引用时从核心前端契约导入。
	core bool
	err  error
}

// generateTypeScriptContract 生成前端使用的契约类型、枚举与常量，source 是契约包相对模块根目录的路径；模块契约引用的核心契约类型从核心前端契约导入。
func (c *contract) generateTypeScriptContract(methods []method, source string) ([]byte, error) {
	emitter := &typeScriptEmitter{contract: c, optional: map[string]bool{}}
	for _, item := range methods {
		for _, parameter := range item.params {
			if parameter.kind == paramQueryStruct {
				emitter.optional[c.localName(parameter.typ)] = true
			}
			emitter.reference(parameter.typ)
		}
		if item.output != nil {
			emitter.reference(item.output)
		}
	}
	// 错误响应体与接口常量只在核心契约中输出。
	if c.base == nil {
		for _, name := range typeScriptRoots {
			emitter.reference(c.pkg.Types.Scope().Lookup(name).Type())
		}
	}
	declarations := map[string]string{}
	// 只按输出的声明判断是否引用核心契约类型。
	emitter.core = false
	for len(emitter.pending) > 0 {
		object := emitter.pending[0]
		emitter.pending = emitter.pending[1:]
		declarations[emitter.name(object)] = emitter.declaration(object)
	}
	if emitter.err != nil {
		return nil, emitter.err
	}
	builder := &strings.Builder{}
	builder.WriteString("// Code generated by appservicegen. DO NOT EDIT.\n\n")
	if c.base == nil {
		fmt.Fprintf(builder, "/** 服务端应用契约的类型、枚举与接口常量，由 %s 生成。 */\n\n", source)
	} else {
		fmt.Fprintf(builder, "/** 服务端应用契约的类型与枚举，由 %s 生成。 */\n", source)
		if emitter.core {
			builder.WriteString("import type * as core from \"@/api/generated/contract\"\n")
		}
		builder.WriteString("\n")
	}
	for _, name := range typeScriptConstants {
		if c.base != nil {
			break
		}
		object, ok := c.pkg.Types.Scope().Lookup(name).(*types.Const)
		if !ok {
			return nil, fmt.Errorf("constant %s not found", name)
		}
		writeTypeScriptDoc(builder, "", stripLeadingName(c.docs[name], name))
		fmt.Fprintf(builder, "export const %s = %s\n\n", name, object.Val().ExactString())
	}
	for _, name := range slices.Sorted(maps.Keys(declarations)) {
		builder.WriteString(declarations[name])
	}
	return []byte(builder.String()), nil
}

// name 返回契约类型在 TypeScript 中的名称。
func (e *typeScriptEmitter) name(object *types.TypeName) string {
	if renamed, ok := typeScriptNames[object.Name()]; ok {
		return renamed
	}
	return object.Name()
}

// reference 返回类型在 TypeScript 中的写法，遇到尚未输出的契约命名类型时加入待输出队列。
func (e *typeScriptEmitter) reference(t types.Type) string {
	switch t := types.Unalias(t).(type) {
	case *types.Basic:
		switch {
		case t.Info()&types.IsString != 0:
			return "string"
		case t.Info()&types.IsBoolean != 0:
			return "boolean"
		case t.Info()&types.IsNumeric != 0:
			return "number"
		}
	case *types.Pointer:
		return e.reference(t.Elem()) + " | null"
	case *types.Slice:
		if basic, ok := t.Elem().(*types.Basic); ok && basic.Kind() == types.Byte {
			return "string"
		}
		element := e.reference(t.Elem())
		if strings.Contains(element, " ") {
			element = "(" + element + ")"
		}
		return element + "[]"
	case *types.Map:
		value := e.reference(t.Elem())
		if key := e.contract.localName(t.Key()); key != "" && len(e.contract.enumsOf(t.Key())) > 0 {
			return "Partial<Record<" + e.reference(t.Key()) + ", " + value + ">>"
		}
		return "Record<string, " + value + ">"
	case *types.Interface:
		if t.Empty() {
			return "unknown"
		}
	case *types.Named:
		object := t.Obj()
		switch object.Pkg().Path() + "." + object.Name() {
		case "time.Time":
			return "string"
		case "encoding/json.RawMessage":
			return "unknown"
		}
		if e.contract.fromBase(t) {
			e.core = true
			return "core." + e.name(object)
		}
		if e.contract.localName(t) != "" {
			if e.seen.Add(object) {
				e.pending = append(e.pending, object)
			}
			return e.name(object)
		}
	}
	if e.err == nil {
		e.err = fmt.Errorf("unsupported TypeScript type %s", t)
	}
	return "unknown"
}

// declaration 输出一个契约命名类型的 TypeScript 声明。
func (e *typeScriptEmitter) declaration(object *types.TypeName) string {
	builder := &strings.Builder{}
	name := e.name(object)
	doc := stripLeadingName(e.contract.docs[object.Name()], object.Name())
	if constants := e.contract.enums[object]; len(constants) > 0 {
		writeTypeScriptDoc(builder, "", doc)
		fmt.Fprintf(builder, "export const %s = {\n", name)
		for _, item := range constants {
			writeTypeScriptDoc(builder, "  ", stripLeadingName(e.contract.docs[item.Name()], item.Name()))
			fmt.Fprintf(builder, "  %s: %s,\n", enumMemberName(object.Name(), item.Name()), typeScriptLiteral(item.Val()))
		}
		builder.WriteString("} as const\n\n")
		writeTypeScriptDoc(builder, "", doc)
		fmt.Fprintf(builder, "export type %s = (typeof %s)[keyof typeof %s]\n\n", name, name, name)
		return builder.String()
	}
	structType, ok := object.Type().Underlying().(*types.Struct)
	if !ok {
		writeTypeScriptDoc(builder, "", doc)
		fmt.Fprintf(builder, "export type %s = %s\n\n", name, e.reference(object.Type().Underlying()))
		return builder.String()
	}
	writeTypeScriptDoc(builder, "", doc)
	fmt.Fprintf(builder, "export interface %s {\n", name)
	e.writeFields(builder, object.Name(), structType, e.optional[object.Name()])
	builder.WriteString("}\n\n")
	return builder.String()
}

// writeFields 按 JSON 编码规则输出结构体字段，未命名的内嵌结构体字段展开到外层。
func (e *typeScriptEmitter) writeFields(builder *strings.Builder, owner string, structType *types.Struct, allOptional bool) {
	for index := range structType.NumFields() {
		field := structType.Field(index)
		if !field.Exported() {
			continue
		}
		jsonTag := reflect.StructTag(structType.Tag(index)).Get("json")
		if jsonTag == "-" {
			continue
		}
		jsonName, options, _ := strings.Cut(jsonTag, ",")
		if field.Embedded() && jsonName == "" {
			embedded, ok := types.Unalias(field.Type()).Underlying().(*types.Struct)
			if !ok {
				e.err = fmt.Errorf("%s: unsupported embedded field %s", owner, field.Name())
				return
			}
			e.writeFields(builder, types.Unalias(field.Type()).(*types.Named).Obj().Name(), embedded, allOptional)
			continue
		}
		if jsonName == "" {
			jsonName = field.Name()
		}
		if !identifierPattern.MatchString(jsonName) {
			jsonName = fmt.Sprintf("%q", jsonName)
		}
		omitEmpty := str.Contains(","+options+",", ",omitempty,", ",omitzero,")
		fieldType := field.Type()
		marker := ""
		if omitEmpty || allOptional {
			marker = "?"
			// 省略空值的指针字段只会缺省，不会为 null。
			if pointer, ok := fieldType.(*types.Pointer); ok && omitEmpty {
				fieldType = pointer.Elem()
			}
		}
		writeTypeScriptDoc(builder, "  ", stripLeadingName(e.contract.docs[owner+"."+field.Name()], field.Name()))
		fmt.Fprintf(builder, "  %s%s: %s\n", jsonName, marker, e.reference(fieldType))
	}
}

// enumMemberName 返回枚举常量在 TypeScript 常量对象中的成员名：常量名以类型名开头且余下部分是合法标识符时去掉类型名前缀。
func enumMemberName(typeName, constantName string) string {
	rest, found := strings.CutPrefix(constantName, typeName)
	if !found || rest == "" || !unicode.IsUpper(rune(rest[0])) {
		return constantName
	}
	return rest
}

// typeScriptLiteral 返回常量值的 TypeScript 字面量。
func typeScriptLiteral(value constant.Value) string {
	if value.Kind() == constant.String {
		return fmt.Sprintf("%q", constant.StringVal(value))
	}
	return value.ExactString()
}

// stripLeadingName 去掉 Go 文档首行开头的标识符。
func stripLeadingName(lines []string, name string) []string {
	if len(lines) == 0 {
		return nil
	}
	result := append([]string(nil), lines...)
	result[0] = strings.TrimSpace(strings.TrimPrefix(result[0], name+" "))
	return result
}

// writeTypeScriptDoc 输出 TSDoc 注释，没有注释时不输出。
func writeTypeScriptDoc(builder *strings.Builder, indent string, lines []string) {
	kept := arr.FilterMap(lines, func(line string) (string, bool) {
		return strings.ReplaceAll(line, "*/", "*\\/"), strings.TrimSpace(line) != ""
	})
	switch len(kept) {
	case 0:
	case 1:
		fmt.Fprintf(builder, "%s/** %s */\n", indent, kept[0])
	default:
		fmt.Fprintf(builder, "%s/**\n", indent)
		for _, line := range kept {
			fmt.Fprintf(builder, "%s * %s\n", indent, line)
		}
		fmt.Fprintf(builder, "%s */\n", indent)
	}
}

// generateTypeScriptOperations 生成前端按契约调用服务端的函数，每个方法一个，路径相对服务端 /api。
func (c *contract) generateTypeScriptOperations(methods []method) []byte {
	builder := &strings.Builder{}
	// namespaces 记录参数与结果类型引用的前端契约命名空间。
	namespaces := map[string]bool{}
	typeName := func(t types.Type) string {
		name := typeScriptParameterType(c, t)
		if namespace, _, found := strings.Cut(name, "."); found {
			namespaces[namespace] = true
		}
		return name
	}
	for _, item := range methods {
		writeTypeScriptDoc(builder, "", stripLeadingName(item.doc, item.name))
		var parameters []string
		var query []string
		body := ""
		for _, parameter := range item.params {
			switch parameter.kind {
			case paramPath:
				parameters = append(parameters, parameter.name+": string")
			case paramQueryScalar:
				parameters = append(parameters, parameter.name+": "+typeName(parameter.typ))
				query = append(query, fmt.Sprintf("%s: %s", parameter.name, parameter.name))
			case paramQueryStruct:
				parameters = append(parameters, "input: "+typeName(parameter.typ))
				fields, _ := c.queryFields(parameter.typ)
				for _, field := range fields {
					key := field.queryName
					if !identifierPattern.MatchString(key) {
						key = fmt.Sprintf("%q", key)
					}
					query = append(query, fmt.Sprintf("%s: input.%s", key, field.jsonName))
				}
			case paramBody:
				parameters = append(parameters, "input: "+typeName(parameter.typ))
				body = "input"
			}
		}
		parameters = append(parameters, "signal?: AbortSignal")
		output := "void"
		if item.output != nil {
			output = typeName(item.output)
		}
		spec := []string{fmt.Sprintf("method: %q", item.route.httpMethod), "path: " + typeScriptPathExpression(item.route.path)}
		if len(query) > 0 {
			spec = append(spec, "query: { "+strings.Join(query, ", ")+" }")
		}
		if body != "" {
			spec = append(spec, "body: "+body)
		}
		fmt.Fprintf(builder, "export function %s(%s) {\n", str.Lcfirst(item.name), strings.Join(parameters, ", "))
		fmt.Fprintf(builder, "  return call<%s>({ %s }, signal)\n}\n\n", output, strings.Join(spec, ", "))
	}
	body := builder.String()
	header := &strings.Builder{}
	header.WriteString("// Code generated by appservicegen. DO NOT EDIT.\n\n")
	header.WriteString("/** 按服务端应用契约调用接口，每个函数在当前登录会话代次中发起请求。 */\n")
	header.WriteString("import { call } from \"@/api/client\"\n\n")
	// 调用函数的参数或结果引用核心或本契约的类型时导入对应的前端契约。
	if namespaces["core"] {
		header.WriteString("import type * as core from \"@/api/generated/contract\"\n")
	}
	if namespaces["contract"] {
		header.WriteString("import type * as contract from \"./contract\"\n")
	}
	header.WriteString("\n")
	return []byte(strings.TrimSuffix(header.String()+body, "\n"))
}

// typeScriptParameterType 返回调用函数参数与结果的 TypeScript 类型，契约类型带 contract 命名空间，模块契约引用的核心契约类型带 core 命名空间。
func typeScriptParameterType(c *contract, t types.Type) string {
	if name := c.localName(t); name != "" {
		if renamed, ok := typeScriptNames[name]; ok {
			name = renamed
		}
		if c.fromBase(t) {
			return "core." + name
		}
		return "contract." + name
	}
	switch t := t.(type) {
	case *types.Basic:
		switch {
		case t.Info()&types.IsString != 0:
			return "string"
		case t.Info()&types.IsBoolean != 0:
			return "boolean"
		}
		return "number"
	}
	return "unknown"
}

// typeScriptPathExpression 将路由路径转换为拼接路径参数的模板字符串。
func typeScriptPathExpression(path string) string {
	if !strings.Contains(path, "{") {
		return fmt.Sprintf("%q", path)
	}
	segments := strings.Split(path, "/")
	for index, segment := range segments {
		if name, found := strings.CutPrefix(segment, "{"); found {
			segments[index] = "${encodeURIComponent(" + strings.TrimSuffix(name, "}") + ")}"
		}
	}
	return "`" + strings.Join(segments, "/") + "`"
}
