package main

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/constant"
	"go/types"
	"reflect"
	"slices"
	"sort"
	"strings"

	"github.com/runforyou-ai/luway/internal/domain"
	"github.com/runforyou-ai/support/arr"
	"github.com/runforyou-ai/support/mapx"
	"github.com/runforyou-ai/support/set"
	"github.com/runforyou-ai/support/str"
)

const (
	realtimeProtocolPath = "github.com/runforyou-ai/luway/internal/realtime/protocol"
	appservicePath       = "github.com/runforyou-ai/luway/internal/appservice"
)

// realtimePreamble 是实时事件契约生成文件中的公共解码片段。
const realtimePreamble = `/** 以十进制字符串传输的非负 64 位整数，解码为 bigint。 */
const int64String = z
  .string()
  .regex(/^(0|[1-9]\d*)$/)
  .transform((value) => BigInt(value))
  .refine((value) => value <= 9223372036854775807n)

/** 返回数组字段的解码模式，缺少或为 null 时解码为空数组。 */
function list<T extends z.ZodType>(item: T) {
  return z.array(item).nullish().transform((items) => items ?? [])
}

`

// realtimeEmitter 从实时协议的事件结构出发，按依赖顺序输出 TypeScript 类型与 Zod 解码模式。
type realtimeEmitter struct {
	protocol *contract
	domain   *contract
	service  *contract
	// frames 按事件结构名记录其事件种类取值。
	frames map[string]string
	out    *strings.Builder
	done   set.Set[string]
	// imports 记录从 contract.ts 引用的枚举常量对象，typeImports 记录只引用类型的契约结构体。
	imports     map[string]bool
	typeImports map[string]bool
	err         error
}

// generateRealtimeContract 生成实时事件契约的 TypeScript 类型、枚举与 Zod 解码模式。
func generateRealtimeContract(protocol, domainContract, service *contract) ([]byte, error) {
	e := &realtimeEmitter{
		protocol: protocol, domain: domainContract, service: service,
		frames: map[string]string{}, out: &strings.Builder{},
		imports: map[string]bool{}, typeImports: map[string]bool{},
	}
	scope := protocol.pkg.Types.Scope()
	typeObject, ok := scope.Lookup("Type").(*types.TypeName)
	if !ok {
		return nil, fmt.Errorf("realtime protocol: type Type not found")
	}
	if err := e.indexFrames(); err != nil {
		return nil, err
	}
	frameNames := mapx.Invert(e.frames)
	var ordered []string
	for _, item := range protocol.enums[typeObject] {
		value := constant.StringVal(item.Val())
		name, ok := frameNames[value]
		if !ok {
			return nil, fmt.Errorf("realtime protocol: event type %s has no frame struct", item.Name())
		}
		ordered = append(ordered, name)
	}
	if len(ordered) != len(e.frames) {
		return nil, fmt.Errorf("realtime protocol: frame structs and event types differ")
	}
	versionObject, ok := scope.Lookup("Version").(*types.Const)
	if !ok {
		return nil, fmt.Errorf("realtime protocol: constant Version not found")
	}
	writeTypeScriptDoc(e.out, "", stripLeadingName(protocol.docs["Version"], "Version"))
	fmt.Fprintf(e.out, "export const Version = %s\n\n", versionObject.Val().ExactString())
	e.out.WriteString(realtimePreamble)
	e.reference(typeObject.Type())
	for _, name := range ordered {
		e.reference(scope.Lookup(name).Type())
	}
	frameDoc := stripLeadingName(protocol.docs["Frame"], "Frame")
	writeTypeScriptDoc(e.out, "", frameDoc)
	fmt.Fprintf(e.out, "export type Frame =\n  | %s\n\n", strings.Join(ordered, "\n  | "))
	writeTypeScriptDoc(e.out, "", []string{"按事件种类解码的事件模式。"})
	fmt.Fprintf(e.out, "export const FrameSchema: z.ZodType<Frame> = z.discriminatedUnion(\"type\", [\n")
	for _, name := range ordered {
		fmt.Fprintf(e.out, "  %sSchema,\n", name)
	}
	e.out.WriteString("])\n")
	if e.err != nil {
		return nil, e.err
	}
	header := &strings.Builder{}
	header.WriteString("// Code generated by appservicegen. DO NOT EDIT.\n\n")
	header.WriteString("/** 实时事件的类型、枚举与 Zod 解码模式，由 internal/realtime/protocol 生成。 */\n")
	header.WriteString("import { z } from \"zod\"\n\n")
	var specifiers []string
	for name := range e.typeImports {
		specifiers = append(specifiers, "type "+name)
	}
	for name := range e.imports {
		specifiers = append(specifiers, name)
	}
	sort.Slice(specifiers, func(i, j int) bool {
		return strings.TrimPrefix(specifiers[i], "type ") < strings.TrimPrefix(specifiers[j], "type ")
	})
	if len(specifiers) > 0 {
		fmt.Fprintf(header, "import { %s } from \"./contract\"\n\n", strings.Join(specifiers, ", "))
	}
	return []byte(header.String() + e.out.String()), nil
}

// indexFrames 从 FrameType 方法体读取每个事件结构返回的事件种类常量。
func (e *realtimeEmitter) indexFrames() error {
	for _, file := range e.protocol.pkg.Syntax {
		for _, declaration := range file.Decls {
			function, ok := declaration.(*ast.FuncDecl)
			if !ok || function.Name.Name != "FrameType" || function.Recv == nil || len(function.Recv.List) != 1 {
				continue
			}
			receiver, ok := function.Recv.List[0].Type.(*ast.Ident)
			if !ok {
				return fmt.Errorf("realtime protocol: FrameType receiver must be a value type")
			}
			var result *ast.Ident
			if len(function.Body.List) == 1 {
				if statement, ok := function.Body.List[0].(*ast.ReturnStmt); ok && len(statement.Results) == 1 {
					result, _ = statement.Results[0].(*ast.Ident)
				}
			}
			if result == nil {
				return fmt.Errorf("realtime protocol: %s.FrameType must return an event type constant", receiver.Name)
			}
			object, ok := e.protocol.pkg.TypesInfo.Uses[result].(*types.Const)
			if !ok || object.Val().Kind() != constant.String {
				return fmt.Errorf("realtime protocol: %s.FrameType must return an event type constant", receiver.Name)
			}
			e.frames[receiver.Name] = constant.StringVal(object.Val())
		}
	}
	return nil
}

// typeKey 返回命名类型跨包唯一的名称。
func typeKey(object *types.TypeName) string {
	return object.Pkg().Path() + "." + object.Name()
}

// reference 返回类型的 TypeScript 写法与 Zod 模式，命名类型首次出现时先输出其声明。
func (e *realtimeEmitter) reference(t types.Type) (string, string) {
	switch t := types.Unalias(t).(type) {
	case *types.Basic:
		switch {
		case t.Info()&types.IsString != 0:
			return "string", "z.string()"
		case t.Info()&types.IsBoolean != 0:
			return "boolean", "z.boolean()"
		case t.Info()&types.IsInteger != 0:
			return "number", "z.int()"
		case t.Info()&types.IsFloat != 0:
			return "number", "z.number()"
		}
	case *types.Slice:
		element, schema := e.reference(t.Elem())
		if strings.Contains(element, " ") {
			element = "(" + element + ")"
		}
		return element + "[]", "list(" + schema + ")"
	case *types.Named:
		object := t.Obj()
		key := typeKey(object)
		switch key {
		case "time.Time":
			return "string", "z.string()"
		case domainPath + ".ConversationChanges":
			e.emitConversationChange()
			return "ConversationChange[]", "z.array(z.enum(ConversationChange))"
		}
		owner := e.owner(object)
		if owner == nil {
			break
		}
		ownObject, _ := owner.pkg.Types.Scope().Lookup(object.Name()).(*types.TypeName)
		if constants := owner.enums[ownObject]; len(constants) > 0 {
			e.emitEnum(owner, object.Name(), constants)
			return object.Name(), "z.enum(" + object.Name() + ")"
		}
		if structType, ok := object.Type().Underlying().(*types.Struct); ok {
			e.emitStruct(owner, object, structType)
			return object.Name(), object.Name() + "Schema"
		}
	}
	if e.err == nil {
		e.err = fmt.Errorf("realtime protocol: unsupported type %s", t)
	}
	return "unknown", "z.unknown()"
}

// owner 返回声明该命名类型的已加载包，不在协议、领域值或应用契约包中时返回 nil。
func (e *realtimeEmitter) owner(object *types.TypeName) *contract {
	switch object.Pkg().Path() {
	case realtimeProtocolPath:
		return e.protocol
	case domainPath:
		return e.domain
	case appservicePath:
		return e.service
	}
	return nil
}

// emitEnum 输出枚举常量对象；应用契约中有同名且取值相同的枚举时从 contract.ts 引用。
func (e *realtimeEmitter) emitEnum(owner *contract, name string, constants []*types.Const) {
	key := owner.pkg.PkgPath + "." + name
	if !e.done.Add(key) {
		return
	}
	values := enumValues(constants)
	if serviceObject, ok := e.service.pkg.Types.Scope().Lookup(name).(*types.TypeName); ok {
		// 应用契约中的类型别名按被引用的领域类型登记常量。
		if named, isNamed := types.Unalias(serviceObject.Type()).(*types.Named); isNamed {
			serviceObject = named.Obj()
		}
		if slices.Equal(values, enumValues(e.service.enums[serviceObject])) {
			e.imports[name] = true
			return
		}
	}
	doc := stripLeadingName(owner.docs[name], name)
	writeTypeScriptDoc(e.out, "", doc)
	fmt.Fprintf(e.out, "export const %s = {\n", name)
	for _, item := range constants {
		writeTypeScriptDoc(e.out, "  ", stripLeadingName(owner.docs[item.Name()], item.Name()))
		fmt.Fprintf(e.out, "  %s: %s,\n", enumMemberName(name, item.Name()), typeScriptLiteral(item.Val()))
	}
	e.out.WriteString("} as const\n\n")
	writeTypeScriptDoc(e.out, "", doc)
	fmt.Fprintf(e.out, "export type %s = (typeof %s)[keyof typeof %s]\n\n", name, name, name)
}

// enumValues 返回枚举常量取值的有序列表。
func enumValues(constants []*types.Const) []string {
	values := arr.Map(constants, func(item *types.Const) string { return item.Val().ExactString() })
	sort.Strings(values)
	return values
}

// emitConversationChange 按 domain.ConversationChanges 的 JSON 编码输出会话变化类别枚举，类别名称由各位常量编码得到。
func (e *realtimeEmitter) emitConversationChange() {
	key := domainPath + ".ConversationChange"
	if !e.done.Add(key) {
		return
	}
	object := e.domain.pkg.Types.Scope().Lookup("ConversationChanges").(*types.TypeName)
	doc := []string{"会话变更通知携带的一种变化类别。"}
	writeTypeScriptDoc(e.out, "", doc)
	e.out.WriteString("export const ConversationChange = {\n")
	for _, item := range e.domain.enums[object] {
		bit, _ := constant.Uint64Val(item.Val())
		encoded, err := json.Marshal(domain.ConversationChanges(bit))
		var names []string
		if err == nil {
			err = json.Unmarshal(encoded, &names)
		}
		if err != nil || len(names) != 1 {
			e.err = fmt.Errorf("realtime protocol: conversation change %s does not encode to one name", item.Name())
			return
		}
		writeTypeScriptDoc(e.out, "  ", stripLeadingName(e.domain.docs[item.Name()], item.Name()))
		fmt.Fprintf(e.out, "  %s: %q,\n", enumMemberName("ConversationChange", item.Name()), names[0])
	}
	e.out.WriteString("} as const\n\n")
	writeTypeScriptDoc(e.out, "", doc)
	e.out.WriteString("export type ConversationChange = (typeof ConversationChange)[keyof typeof ConversationChange]\n\n")
}

// realtimeField 是结构体字段在 TypeScript 中的声明与 Zod 模式。
type realtimeField struct {
	name     string
	doc      []string
	optional bool
	tsType   string
	schema   string
}

// emitStruct 输出结构体的接口与 Zod 模式；事件结构额外带事件种类字段，应用契约结构体只引用其类型。
func (e *realtimeEmitter) emitStruct(owner *contract, object *types.TypeName, structType *types.Struct) {
	key := typeKey(object)
	if !e.done.Add(key) {
		return
	}
	name := object.Name()
	var fields []realtimeField
	if value, ok := e.frames[name]; ok && owner == e.protocol {
		fields = append(fields, realtimeField{name: "type", tsType: fmt.Sprintf("%q", value), schema: fmt.Sprintf("z.literal(%q)", value)})
	}
	for index := range structType.NumFields() {
		field, ok := e.field(owner, name, structType, index)
		if ok {
			fields = append(fields, field)
		}
	}
	if owner == e.service {
		e.typeImports[name] = true
	} else {
		writeTypeScriptDoc(e.out, "", stripLeadingName(owner.docs[name], name))
		fmt.Fprintf(e.out, "export interface %s {\n", name)
		for _, field := range fields {
			writeTypeScriptDoc(e.out, "  ", field.doc)
			marker := ""
			if field.optional {
				marker = "?"
			}
			fmt.Fprintf(e.out, "  %s%s: %s\n", field.name, marker, field.tsType)
		}
		e.out.WriteString("}\n\n")
	}
	writeTypeScriptDoc(e.out, "", []string{fmt.Sprintf("%s 的解码模式。", name)})
	fmt.Fprintf(e.out, "export const %sSchema = z.object({\n", name)
	for _, field := range fields {
		fmt.Fprintf(e.out, "  %s: %s,\n", field.name, field.schema)
	}
	if owner == e.service {
		fmt.Fprintf(e.out, "}) satisfies z.ZodType<%s>\n\n", name)
	} else {
		e.out.WriteString("})\n\n")
	}
}

// field 按 JSON 编码规则返回结构体字段：省略空值的标量缺省时取零值，省略空值的指针与枚举可缺省，数组缺省或为 null 时取空数组，带 string 选项的 int64 以十进制字符串传输。
func (e *realtimeEmitter) field(owner *contract, structName string, structType *types.Struct, index int) (realtimeField, bool) {
	field := structType.Field(index)
	jsonTag := reflect.StructTag(structType.Tag(index)).Get("json")
	if !field.Exported() || jsonTag == "-" {
		return realtimeField{}, false
	}
	if field.Embedded() {
		e.err = fmt.Errorf("realtime protocol: %s: unsupported embedded field %s", structName, field.Name())
		return realtimeField{}, false
	}
	jsonName, options, _ := strings.Cut(jsonTag, ",")
	if jsonName == "" {
		jsonName = field.Name()
	}
	if !identifierPattern.MatchString(jsonName) {
		jsonName = fmt.Sprintf("%q", jsonName)
	}
	optionSet := "," + options + ","
	omitEmpty := str.Contains(optionSet, ",omitempty,", ",omitzero,")
	result := realtimeField{name: jsonName, doc: stripLeadingName(owner.docs[structName+"."+field.Name()], field.Name())}
	fieldType := types.Unalias(field.Type())
	if strings.Contains(optionSet, ",string,") {
		if basic, ok := fieldType.(*types.Basic); !ok || basic.Kind() != types.Int64 {
			e.err = fmt.Errorf("realtime protocol: %s.%s: string option only supports int64", structName, field.Name())
		}
		result.tsType, result.schema = "bigint", "int64String"
		return result, true
	}
	if pointer, ok := fieldType.(*types.Pointer); ok {
		result.tsType, result.schema = e.reference(pointer.Elem())
		if omitEmpty {
			result.optional, result.schema = true, result.schema+".optional()"
		} else {
			result.tsType, result.schema = result.tsType+" | null", result.schema+".nullable()"
		}
		return result, true
	}
	result.tsType, result.schema = e.reference(fieldType)
	if named, ok := fieldType.(*types.Named); ok && typeKey(named.Obj()) == domainPath+".ConversationChanges" {
		// 含未知类别的集合无法表示，解码为缺省，接收方按全部类别处理。
		result.optional, result.schema = true, result.schema+".optional().catch(undefined)"
		return result, true
	}
	if !omitEmpty {
		return result, true
	}
	switch underlying := fieldType.Underlying().(type) {
	case *types.Slice:
	case *types.Basic:
		if _, named := fieldType.(*types.Named); named {
			result.optional, result.schema = true, result.schema+".optional()"
			break
		}
		switch {
		case underlying.Info()&types.IsString != 0:
			result.schema += `.default("")`
		case underlying.Info()&types.IsBoolean != 0:
			result.schema += ".default(false)"
		default:
			result.schema += ".default(0)"
		}
	default:
		e.err = fmt.Errorf("realtime protocol: %s.%s: unsupported omitempty field", structName, field.Name())
	}
	return result, true
}
